package no.netcom.ninja.core.system.tuxedo.service.parameters;

import no.netcom.ninja.core.referencetables.SystemDefaultsReferenceTable;
import no.netcom.ninja.core.system.tuxedo.exception.EnvironmentException;
import no.netcom.ninja.core.system.tuxedo.exception.FMLManipulationException;
import no.netcom.ninja.core.util.TypeConverter;


/**
 * @author  Ninja - Generated by Ninja tools : created on 31-01-2020 10:37:03. Fokus 315 drop 1
 */
public class BlRvrsLoanStlInput extends ServiceInput {
	/**
	 * Creates a new instance of BlRvrsLoanStlInput
	 *
	 * @throws EnvironmentException
	 * @throws FMLManipulationException
	 */
	public BlRvrsLoanStlInput() throws EnvironmentException, FMLManipulationException {

		fmlBuffer = new FmlField[206];

		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoDirective(), 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getDefaultFokusOperatorId(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, SystemDefaultsReferenceTable.getApplicationId(), 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, SystemDefaultsReferenceTable.getTuxedoTransactionMode(), 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4, SystemDefaultsReferenceTable.getDefaultMarket(), 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, SystemDefaultsReferenceTable.getFokusEnvironmentCode(), 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoSessionId(), 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoOnlineTrxNo(), 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("ROWID", FmlField.TYPE_STRING, 19, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 17, 1);
		this.fmlBuffer[18] = new FmlField("SUBSCRIBER_NO", FmlField.TYPE_STRING, 21, null, 18, 1);
		this.fmlBuffer[19] = new FmlField("SUBSCRIBER_ID", FmlField.TYPE_INTEGER, -1, null, 19, 1);
		this.fmlBuffer[20] = new FmlField("FTR_EFFECTIVE_DATE", FmlField.TYPE_STRING, 9, null, 20, 1);
		this.fmlBuffer[21] = new FmlField("FTR_EXPIRATION_DATE", FmlField.TYPE_STRING, 9, null, 21, 1);
		this.fmlBuffer[22] = new FmlField("FTR_EXP_RSN_CODE", FmlField.TYPE_BYTE, -1, null, 22, 1);
		this.fmlBuffer[23] = new FmlField("LOAN_VER_NO", FmlField.TYPE_INTEGER, -1, null, 23, 1);
		this.fmlBuffer[24] = new FmlField("LOAN_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 24, 1);
		this.fmlBuffer[25] = new FmlField("FTR_EFF_RSN_CODE", FmlField.TYPE_BYTE, -1, null, 25, 1);
		this.fmlBuffer[26] = new FmlField("FTR_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 26, 1);
		this.fmlBuffer[27] = new FmlField("SOC_LOAN_0VROWID", FmlField.TYPE_STRING, 19, null, 27, 1);
		this.fmlBuffer[28] = new FmlField("SOC", FmlField.TYPE_STRING, 10, null, 28, 1);
		this.fmlBuffer[29] = new FmlField("EFFECTIVE_DATE", FmlField.TYPE_STRING, 9, null, 29, 1);
		this.fmlBuffer[30] = new FmlField("SOC_LOAN_0VLOAN_VER_NO", FmlField.TYPE_INTEGER, -1, null, 30, 1);
		this.fmlBuffer[31] = new FmlField("FULL_RATE", FmlField.TYPE_DOUBLE, -1, null, 31, 1);
		this.fmlBuffer[32] = new FmlField("FULL_RT_TAX_CATEG", FmlField.TYPE_BYTE, -1, null, 32, 1);
		this.fmlBuffer[33] = new FmlField("FULL_RT_INC_TAX", FmlField.TYPE_BYTE, -1, null, 33, 1);
		this.fmlBuffer[34] = new FmlField("FIRST_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 34, 1);
		this.fmlBuffer[35] = new FmlField("OTHER_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 35, 1);
		this.fmlBuffer[36] = new FmlField("HANDLING_FEE", FmlField.TYPE_DOUBLE, -1, null, 36, 1);
		this.fmlBuffer[37] = new FmlField("HNDL_FEE_POLICY", FmlField.TYPE_BYTE, -1, null, 37, 1);
		this.fmlBuffer[38] = new FmlField("HANDLING_FEATURE", FmlField.TYPE_STRING, 7, null, 38, 1);
		this.fmlBuffer[39] = new FmlField("INSTALLMENT_FEATURE", FmlField.TYPE_STRING, 7, null, 39, 1);
		this.fmlBuffer[40] = new FmlField("FULL_PMNT_FEATURE", FmlField.TYPE_STRING, 7, null, 40, 1);
		this.fmlBuffer[41] = new FmlField("CRDT_FEATURE", FmlField.TYPE_STRING, 7, null, 41, 1);
		this.fmlBuffer[42] = new FmlField("NO_OF_INSTALLMENTS", FmlField.TYPE_SHORT, -1, null, 42, 1);
		this.fmlBuffer[43] = new FmlField("GRACE_PERIOD", FmlField.TYPE_SHORT, -1, null, 43, 1);
		this.fmlBuffer[44] = new FmlField("EXPIRATION_DATE", FmlField.TYPE_STRING, 9, null, 44, 1);
		this.fmlBuffer[45] = new FmlField("SETTLE_ON_CANCEL", FmlField.TYPE_BYTE, -1, null, 45, 1);
		this.fmlBuffer[46] = new FmlField("FLEX_MIN_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 46, 1);
		this.fmlBuffer[47] = new FmlField("FLEX_MAX_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 47, 1);
		this.fmlBuffer[48] = new FmlField("FLEX_MIN_NO_INSTALL", FmlField.TYPE_SHORT, -1, null, 48, 1);
		this.fmlBuffer[49] = new FmlField("FLEX_MAX_NO_INSTALL", FmlField.TYPE_SHORT, -1, null, 49, 1);
		this.fmlBuffer[50] = new FmlField("LOAN_ROUND_UNIT", FmlField.TYPE_SHORT, -1, null, 50, 1);
		this.fmlBuffer[51] = new FmlField("SUB_LOAN_0VROWID", FmlField.TYPE_STRING, 19, null, 51, 1);
		this.fmlBuffer[52] = new FmlField("SUB_LOAN_0VSUBSCRIBER_ID", FmlField.TYPE_INTEGER, -1, null, 52, 1);
		this.fmlBuffer[53] = new FmlField("SUB_LOAN_0VLOAN_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 53, 1);
		this.fmlBuffer[54] = new FmlField("SUB_LOAN_0VLOAN_VER_NO", FmlField.TYPE_INTEGER, -1, null, 54, 1);
		this.fmlBuffer[55] = new FmlField("SUB_LOAN_0VSOC", FmlField.TYPE_STRING, 10, null, 55, 1);
		this.fmlBuffer[56] = new FmlField("SUB_LOAN_0VEFFECTIVE_DATE", FmlField.TYPE_STRING, 9, null, 56, 1);
		this.fmlBuffer[57] = new FmlField("FULL_AMT", FmlField.TYPE_DOUBLE, -1, null, 57, 1);
		this.fmlBuffer[58] = new FmlField("CHARGED_AMT", FmlField.TYPE_DOUBLE, -1, null, 58, 1);
		this.fmlBuffer[59] = new FmlField("CHARGED_FEE_AMT", FmlField.TYPE_DOUBLE, -1, null, 59, 1);
		this.fmlBuffer[60] = new FmlField("UD_CHARGE_AMT", FmlField.TYPE_DOUBLE, -1, null, 60, 1);
		this.fmlBuffer[61] = new FmlField("UD_FEE_AMT", FmlField.TYPE_DOUBLE, -1, null, 61, 1);
		this.fmlBuffer[62] = new FmlField("UD_NO_INSTALL", FmlField.TYPE_SHORT, -1, null, 62, 1);
		this.fmlBuffer[63] = new FmlField("UD_LAST_DATE_CRG", FmlField.TYPE_STRING, 9, null, 63, 1);
		this.fmlBuffer[64] = new FmlField("LAST_BILL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 64, 1);
		this.fmlBuffer[65] = new FmlField("LAST_DATE_OF_CRG", FmlField.TYPE_STRING, 9, null, 65, 1);
		this.fmlBuffer[66] = new FmlField("NO_CHARGED_INSTL", FmlField.TYPE_SHORT, -1, null, 66, 1);
		this.fmlBuffer[67] = new FmlField("HANDLE_IND", FmlField.TYPE_BYTE, -1, null, 67, 1);
		this.fmlBuffer[68] = new FmlField("SUB_LOAN_0VEXPIRATION_DATE", FmlField.TYPE_STRING, 9, null, 68, 1);
		this.fmlBuffer[69] = new FmlField("SOURCE_MSISDN", FmlField.TYPE_STRING, 21, null, 69, 1);
		this.fmlBuffer[70] = new FmlField("SUB_LOAN_0VFIRST_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 70, 1);
		this.fmlBuffer[71] = new FmlField("SUB_LOAN_0VOTHER_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 71, 1);
		this.fmlBuffer[72] = new FmlField("LAST_INSTALL_RATE", FmlField.TYPE_DOUBLE, -1, null, 72, 1);
		this.fmlBuffer[73] = new FmlField("SUB_LOAN_0VNO_OF_INSTALLMENTS", FmlField.TYPE_SHORT, -1, null, 73, 1);
		this.fmlBuffer[74] = new FmlField("SOC_9VROWID", FmlField.TYPE_STRING, 19, null, 74, 1);
		this.fmlBuffer[75] = new FmlField("SOC_DESCRIPTION", FmlField.TYPE_STRING, 31, null, 75, 1);
		this.fmlBuffer[76] = new FmlField("ALLOW_SWITCH", FmlField.TYPE_BYTE, -1, null, 76, 1);
		this.fmlBuffer[77] = new FmlField("FLEXIBLE_LOAN_IND", FmlField.TYPE_BYTE, -1, null, 77, 1);
		this.fmlBuffer[78] = new FmlField("PCHARGERECROWID", FmlField.TYPE_STRING, 19, null, 78, 1);
		this.fmlBuffer[79] = new FmlField("ROOT_BAN", FmlField.TYPE_INTEGER, -1, null, 79, 1);
		this.fmlBuffer[80] = new FmlField("PCHARGERECBAN", FmlField.TYPE_INTEGER, -1, null, 80, 1);
		this.fmlBuffer[81] = new FmlField("ACTV_BILL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 81, 1);
		this.fmlBuffer[82] = new FmlField("ENT_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 82, 1);
		this.fmlBuffer[83] = new FmlField("ACTV_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 83, 1);
		this.fmlBuffer[84] = new FmlField("SYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 84, 1);
		this.fmlBuffer[85] = new FmlField("SYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 85, 1);
		this.fmlBuffer[86] = new FmlField("PCHARGERECOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 86, 1);
		this.fmlBuffer[87] = new FmlField("PCHARGERECAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 87, 1);
		this.fmlBuffer[88] = new FmlField("DL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 88, 1);
		this.fmlBuffer[89] = new FmlField("DL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 89, 1);
		this.fmlBuffer[90] = new FmlField("VOUCHER_NUM", FmlField.TYPE_STRING, 14, null, 90, 1);
		this.fmlBuffer[91] = new FmlField("PCHARGERECSUBSCRIBER_NO", FmlField.TYPE_STRING, 21, null, 91, 1);
		this.fmlBuffer[92] = new FmlField("DEPARTMENT", FmlField.TYPE_STRING, 5, null, 92, 1);
		this.fmlBuffer[93] = new FmlField("ORG_CODE", FmlField.TYPE_STRING, 6, null, 93, 1);
		this.fmlBuffer[94] = new FmlField("PRODUCT_TYPE", FmlField.TYPE_STRING, 4, null, 94, 1);
		this.fmlBuffer[95] = new FmlField("SUB_MARKET_CD", FmlField.TYPE_STRING, 4, null, 95, 1);
		this.fmlBuffer[96] = new FmlField("PRIOD_CVRG_ST_DATE", FmlField.TYPE_STRING, 9, null, 96, 1);
		this.fmlBuffer[97] = new FmlField("PRIOD_CVRG_ND_DATE", FmlField.TYPE_STRING, 9, null, 97, 1);
		this.fmlBuffer[98] = new FmlField("CHG_CREATION_DATE", FmlField.TYPE_STRING, 9, null, 98, 1);
		this.fmlBuffer[99] = new FmlField("PCHARGERECEFFECTIVE_DATE", FmlField.TYPE_STRING, 9, null, 99, 1);
		this.fmlBuffer[100] = new FmlField("FINANCE_EFF_DATE", FmlField.TYPE_STRING, 9, null, 100, 1);
		this.fmlBuffer[101] = new FmlField("LAST_RG_RC_DATE", FmlField.TYPE_STRING, 9, null, 101, 1);
		this.fmlBuffer[102] = new FmlField("ACTV_DATE", FmlField.TYPE_STRING, 9, null, 102, 1);
		this.fmlBuffer[103] = new FmlField("ACTV_CODE", FmlField.TYPE_STRING, 5, null, 103, 1);
		this.fmlBuffer[104] = new FmlField("ACTV_REASON_CODE", FmlField.TYPE_STRING, 7, null, 104, 1);
		this.fmlBuffer[105] = new FmlField("ACTV_AMT", FmlField.TYPE_DOUBLE, -1, null, 105, 1);
		this.fmlBuffer[106] = new FmlField("DURATION", FmlField.TYPE_DOUBLE, -1, null, 106, 1);
		this.fmlBuffer[107] = new FmlField("NUM_OF_CALLS", FmlField.TYPE_INTEGER, -1, null, 107, 1);
		this.fmlBuffer[108] = new FmlField("FEATURE_CODE", FmlField.TYPE_STRING, 7, null, 108, 1);
		this.fmlBuffer[109] = new FmlField("FTR_REVENUE_CODE", FmlField.TYPE_STRING, 4, null, 109, 1);
		this.fmlBuffer[110] = new FmlField("FEATURE_CATEGORY", FmlField.TYPE_STRING, 5, null, 110, 1);
		this.fmlBuffer[111] = new FmlField("SECONDARY_FEATURE_CD", FmlField.TYPE_STRING, 7, null, 111, 1);
		this.fmlBuffer[112] = new FmlField("AU_RATING_SCHEME_IND", FmlField.TYPE_BYTE, -1, null, 112, 1);
		this.fmlBuffer[113] = new FmlField("BALANCE_IMPACT_CODE", FmlField.TYPE_BYTE, -1, null, 113, 1);
		this.fmlBuffer[114] = new FmlField("PCHARGERECSOC", FmlField.TYPE_STRING, 10, null, 114, 1);
		this.fmlBuffer[115] = new FmlField("SOC_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 115, 1);
		this.fmlBuffer[116] = new FmlField("SOC_VER_NO", FmlField.TYPE_INTEGER, -1, null, 116, 1);
		this.fmlBuffer[117] = new FmlField("SOC_DATE", FmlField.TYPE_STRING, 9, null, 117, 1);
		this.fmlBuffer[118] = new FmlField("SERVICE_TYPE", FmlField.TYPE_BYTE, -1, null, 118, 1);
		this.fmlBuffer[119] = new FmlField("SERVICE_FTR_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 119, 1);
		this.fmlBuffer[120] = new FmlField("TOLL_RS_CODE", FmlField.TYPE_STRING, 10, null, 120, 1);
		this.fmlBuffer[121] = new FmlField("SOURCE_APPL_CODE", FmlField.TYPE_BYTE, -1, null, 121, 1);
		this.fmlBuffer[122] = new FmlField("ASGN_TO_BILL_APPL_CD", FmlField.TYPE_BYTE, -1, null, 122, 1);
		this.fmlBuffer[123] = new FmlField("INV_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 123, 1);
		this.fmlBuffer[124] = new FmlField("VAT_AMT", FmlField.TYPE_DOUBLE, -1, null, 124, 1);
		this.fmlBuffer[125] = new FmlField("VAT_EXMP_AMT", FmlField.TYPE_DOUBLE, -1, null, 125, 1);
		this.fmlBuffer[126] = new FmlField("TAX_CODE", FmlField.TYPE_BYTE, -1, null, 126, 1);
		this.fmlBuffer[127] = new FmlField("VAT_PERCENT_RATE", FmlField.TYPE_DOUBLE, -1, null, 127, 1);
		this.fmlBuffer[128] = new FmlField("VAT_EXMP_IND", FmlField.TYPE_BYTE, -1, null, 128, 1);
		this.fmlBuffer[129] = new FmlField("RC_FTR_PRE_PROR_AMT", FmlField.TYPE_DOUBLE, -1, null, 129, 1);
		this.fmlBuffer[130] = new FmlField("BEFORE_DISCNT_AMT", FmlField.TYPE_DOUBLE, -1, null, 130, 1);
		this.fmlBuffer[131] = new FmlField("DISCOUNT_AMT", FmlField.TYPE_DOUBLE, -1, null, 131, 1);
		this.fmlBuffer[132] = new FmlField("DISCOUNT_PCT", FmlField.TYPE_DOUBLE, -1, null, 132, 1);
		this.fmlBuffer[133] = new FmlField("DISCOUNT_CODE", FmlField.TYPE_STRING, 10, null, 133, 1);
		this.fmlBuffer[134] = new FmlField("CREDIT_LEVEL", FmlField.TYPE_BYTE, -1, null, 134, 1);
		this.fmlBuffer[135] = new FmlField("CRG_QUANTITY", FmlField.TYPE_SHORT, -1, null, 135, 1);
		this.fmlBuffer[136] = new FmlField("AU_ISSUE_CODE", FmlField.TYPE_STRING, 7, null, 136, 1);
		this.fmlBuffer[137] = new FmlField("AU_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 137, 1);
		this.fmlBuffer[138] = new FmlField("ACTION_DIRECTION_CD", FmlField.TYPE_BYTE, -1, null, 138, 1);
		this.fmlBuffer[139] = new FmlField("MANUAL_OVERRIDE_IND", FmlField.TYPE_BYTE, -1, null, 139, 1);
		this.fmlBuffer[140] = new FmlField("MEMO_ID", FmlField.TYPE_INTEGER, -1, null, 140, 1);
		this.fmlBuffer[141] = new FmlField("BL_IGNORE_IND", FmlField.TYPE_BYTE, -1, null, 141, 1);
		this.fmlBuffer[142] = new FmlField("CHARGE_TYPE", FmlField.TYPE_BYTE, -1, null, 142, 1);
		this.fmlBuffer[143] = new FmlField("UTC_DISCOUNT_TYPE", FmlField.TYPE_STRING, 3, null, 143, 1);
		this.fmlBuffer[144] = new FmlField("FRWD_FM_BILL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 144, 1);
		this.fmlBuffer[145] = new FmlField("CHG_GROUP_LEVEL", FmlField.TYPE_BYTE, -1, null, 145, 1);
		this.fmlBuffer[146] = new FmlField("CHG_GROUP_ID", FmlField.TYPE_INTEGER, -1, null, 146, 1);
		this.fmlBuffer[147] = new FmlField("CHARGE_HIST_IND", FmlField.TYPE_BYTE, -1, null, 147, 1);
		this.fmlBuffer[148] = new FmlField("UTC_FROM_TO_BAN", FmlField.TYPE_INTEGER, -1, null, 148, 1);
		this.fmlBuffer[149] = new FmlField("UTC_FROM_SUBSCRIBER", FmlField.TYPE_STRING, 21, null, 149, 1);
		this.fmlBuffer[150] = new FmlField("BILL_PROD_GRP", FmlField.TYPE_STRING, 3, null, 150, 1);
		this.fmlBuffer[151] = new FmlField("UTC_IND", FmlField.TYPE_BYTE, -1, null, 151, 1);
		this.fmlBuffer[152] = new FmlField("ORIG_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 152, 1);
		this.fmlBuffer[153] = new FmlField("CHANNEL_SEIZURE_DT", FmlField.TYPE_STRING, 15, null, 153, 1);
		this.fmlBuffer[154] = new FmlField("MESSAGE_SWITCH_ID", FmlField.TYPE_STRING, 8, null, 154, 1);
		this.fmlBuffer[155] = new FmlField("MESSAGE_IDENTIFIER", FmlField.TYPE_STRING, 25, null, 155, 1);
		this.fmlBuffer[156] = new FmlField("NO_OF_INSTALL_FROM", FmlField.TYPE_SHORT, -1, null, 156, 1);
		this.fmlBuffer[157] = new FmlField("NO_OF_INSTALL_TO", FmlField.TYPE_SHORT, -1, null, 157, 1);
		this.fmlBuffer[158] = new FmlField("TOTAL_NO_OF_INSTALL", FmlField.TYPE_SHORT, -1, null, 158, 1);
		this.fmlBuffer[159] = new FmlField("RMS_INV_STORE_ID", FmlField.TYPE_STRING, 5, null, 159, 1);
		this.fmlBuffer[160] = new FmlField("RMS_INV_ID", FmlField.TYPE_INTEGER, -1, null, 160, 1);
		this.fmlBuffer[161] = new FmlField("RMS_INV_LINE_SEQ", FmlField.TYPE_SHORT, -1, null, 161, 1);
		this.fmlBuffer[162] = new FmlField("RMS_INV_SUBLN_SEQ", FmlField.TYPE_SHORT, -1, null, 162, 1);
		this.fmlBuffer[163] = new FmlField("RMS_INV_ACTV_TYPE", FmlField.TYPE_BYTE, -1, null, 163, 1);
		this.fmlBuffer[164] = new FmlField("BILL_COMMENT", FmlField.TYPE_STRING, 501, null, 164, 1);
		this.fmlBuffer[165] = new FmlField("CONV_RUN_NO", FmlField.TYPE_SHORT, -1, null, 165, 1);
		this.fmlBuffer[166] = new FmlField("ADJ_MSG_BILL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 166, 1);
		this.fmlBuffer[167] = new FmlField("DESIGNATED_INV", FmlField.TYPE_STRING, 14, null, 167, 1);
		this.fmlBuffer[168] = new FmlField("DESIGNATED_ITEM", FmlField.TYPE_INTEGER, -1, null, 168, 1);
		this.fmlBuffer[169] = new FmlField("BILL_RELEVANCE_IND", FmlField.TYPE_BYTE, -1, null, 169, 1);
		this.fmlBuffer[170] = new FmlField("NUM_OF_DAYS_PYM_LATE", FmlField.TYPE_SHORT, -1, null, 170, 1);
		this.fmlBuffer[171] = new FmlField("PERCENTAGE_RATE", FmlField.TYPE_DOUBLE, -1, null, 171, 1);
		this.fmlBuffer[172] = new FmlField("BILL_NUM_FOR_LATE_PYM", FmlField.TYPE_STRING, 14, null, 172, 1);
		this.fmlBuffer[173] = new FmlField("ORIG_OPER_ID", FmlField.TYPE_INTEGER, -1, null, 173, 1);
		this.fmlBuffer[174] = new FmlField("DISC_UTC_AMT", FmlField.TYPE_DOUBLE, -1, null, 174, 1);
		this.fmlBuffer[175] = new FmlField("DISC_UTC_VAT", FmlField.TYPE_DOUBLE, -1, null, 175, 1);
		this.fmlBuffer[176] = new FmlField("CHRG_AMT_PRD_1", FmlField.TYPE_DOUBLE, -1, null, 176, 1);
		this.fmlBuffer[177] = new FmlField("CHRG_AMT_PRD_2", FmlField.TYPE_DOUBLE, -1, null, 177, 1);
		this.fmlBuffer[178] = new FmlField("MATCH_TIER_LEVEL", FmlField.TYPE_SHORT, -1, null, 178, 1);
		this.fmlBuffer[179] = new FmlField("TML_UTC_IND", FmlField.TYPE_BYTE, -1, null, 179, 1);
		this.fmlBuffer[180] = new FmlField("ACT_CODE", FmlField.TYPE_STRING, 4, null, 180, 1);
		this.fmlBuffer[181] = new FmlField("ACT_REASON", FmlField.TYPE_STRING, 5, null, 181, 1);
		this.fmlBuffer[182] = new FmlField("SUSP_RC_RATE_TYPE", FmlField.TYPE_BYTE, -1, null, 182, 1);
		this.fmlBuffer[183] = new FmlField("MEMO_CTN", FmlField.TYPE_STRING, 21, null, 183, 1);
		this.fmlBuffer[184] = new FmlField("USER_TEXT", FmlField.TYPE_STRING, 2001, null, 184, 1);
		this.fmlBuffer[185] = new FmlField("MEMO_SOURCE", FmlField.TYPE_BYTE, -1, null, 185, 1);
		this.fmlBuffer[186] = new FmlField("PARAM_COUNT", FmlField.TYPE_INTEGER, -1, null, 186, 1);
		this.fmlBuffer[187] = new FmlField("P1", FmlField.TYPE_STRING, 51, null, 187, 1);
		this.fmlBuffer[188] = new FmlField("P2", FmlField.TYPE_STRING, 51, null, 188, 1);
		this.fmlBuffer[189] = new FmlField("P3", FmlField.TYPE_STRING, 51, null, 189, 1);
		this.fmlBuffer[190] = new FmlField("P4", FmlField.TYPE_STRING, 51, null, 190, 1);
		this.fmlBuffer[191] = new FmlField("P5", FmlField.TYPE_STRING, 51, null, 191, 1);
		this.fmlBuffer[192] = new FmlField("P6", FmlField.TYPE_STRING, 51, null, 192, 1);
		this.fmlBuffer[193] = new FmlField("P7", FmlField.TYPE_STRING, 51, null, 193, 1);
		this.fmlBuffer[194] = new FmlField("P8", FmlField.TYPE_STRING, 51, null, 194, 1);
		this.fmlBuffer[195] = new FmlField("P9", FmlField.TYPE_STRING, 51, null, 195, 1);
		this.fmlBuffer[196] = new FmlField("P10", FmlField.TYPE_STRING, 51, null, 196, 1);
		this.fmlBuffer[197] = new FmlField("MEMO_AMT", FmlField.TYPE_DOUBLE, -1, null, 197, 1);
		this.fmlBuffer[198] = new FmlField("RMS_ACT_CODE", FmlField.TYPE_STRING, 5, null, 198, 1);
		this.fmlBuffer[199] = new FmlField("CHARGE_AMT", FmlField.TYPE_DOUBLE, -1, null, 199, 1);
		this.fmlBuffer[200] = new FmlField("CHARGE_AMT_IND", FmlField.TYPE_BYTE, -1, null, 200, 1);
		this.fmlBuffer[201] = new FmlField("WAIVE_REASON", FmlField.TYPE_STRING, 7, null, 201, 1);
		this.fmlBuffer[202] = new FmlField("WAIVE_IND", FmlField.TYPE_BYTE, -1, null, 202, 1);
		this.fmlBuffer[203] = new FmlField("TOTAL_ADJ_AMT", FmlField.TYPE_DOUBLE, -1, null, 203, 1);
		this.fmlBuffer[204] = new FmlField("RM_INSTALLMENTS", FmlField.TYPE_SHORT, -1, null, 204, 1);
		this.fmlBuffer[205] = new FmlField("VAT_TOTAL_AMT", FmlField.TYPE_DOUBLE, -1, null, 205, 1);
	} // End of constractor

	public Integer get_GENERATION() throws FMLManipulationException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws FMLManipulationException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws FMLManipulationException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws FMLManipulationException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws FMLManipulationException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[15].setValue(0, value); }


	public String get_ROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[16].getValue(0)); }
	public void set_ROWID(String value) throws FMLManipulationException { this.fmlBuffer[16].setValue(0, value); }


	public Integer get_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[17].getValue(0)); }
	public void set_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[17].setValue(0, value); }


	public String get_SUBSCRIBER_NO() throws FMLManipulationException { return ((String) this.fmlBuffer[18].getValue(0)); }
	public void set_SUBSCRIBER_NO(String value) throws FMLManipulationException { this.fmlBuffer[18].setValue(0, value); }


	public Integer get_SUBSCRIBER_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[19].getValue(0)); }
	public void set_SUBSCRIBER_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[19].setValue(0, value); }


	public String get_FTR_EFFECTIVE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[20].getValue(0)); }
	public void set_FTR_EFFECTIVE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[20].setValue(0, value); }


	public String get_FTR_EXPIRATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[21].getValue(0)); }
	public void set_FTR_EXPIRATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[21].setValue(0, value); }


	public String get_FTR_EXP_RSN_CODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[22].getValue(0))); }
	public void set_FTR_EXP_RSN_CODE(String value) throws FMLManipulationException { this.fmlBuffer[22].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_LOAN_VER_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[23].getValue(0)); }
	public void set_LOAN_VER_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[23].setValue(0, value); }


	public Integer get_LOAN_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[24].getValue(0)); }
	public void set_LOAN_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[24].setValue(0, value); }


	public String get_FTR_EFF_RSN_CODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[25].getValue(0))); }
	public void set_FTR_EFF_RSN_CODE(String value) throws FMLManipulationException { this.fmlBuffer[25].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_FTR_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[26].getValue(0)); }
	public void set_FTR_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[26].setValue(0, value); }


	public String get_SOC_LOAN_0VROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[27].getValue(0)); }
	public void set_SOC_LOAN_0VROWID(String value) throws FMLManipulationException { this.fmlBuffer[27].setValue(0, value); }


	public String get_SOC() throws FMLManipulationException { return ((String) this.fmlBuffer[28].getValue(0)); }
	public void set_SOC(String value) throws FMLManipulationException { this.fmlBuffer[28].setValue(0, value); }


	public String get_EFFECTIVE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[29].getValue(0)); }
	public void set_EFFECTIVE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[29].setValue(0, value); }


	public Integer get_SOC_LOAN_0VLOAN_VER_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[30].getValue(0)); }
	public void set_SOC_LOAN_0VLOAN_VER_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[30].setValue(0, value); }


	public Double get_FULL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[31].getValue(0)); }
	public void set_FULL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[31].setValue(0, value); }


	public String get_FULL_RT_TAX_CATEG() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[32].getValue(0))); }
	public void set_FULL_RT_TAX_CATEG(String value) throws FMLManipulationException { this.fmlBuffer[32].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_FULL_RT_INC_TAX() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[33].getValue(0))); }
	public void set_FULL_RT_INC_TAX(String value) throws FMLManipulationException { this.fmlBuffer[33].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_FIRST_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[34].getValue(0)); }
	public void set_FIRST_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[34].setValue(0, value); }


	public Double get_OTHER_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[35].getValue(0)); }
	public void set_OTHER_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[35].setValue(0, value); }


	public Double get_HANDLING_FEE() throws FMLManipulationException { return ((Double) this.fmlBuffer[36].getValue(0)); }
	public void set_HANDLING_FEE(Double value) throws FMLManipulationException { this.fmlBuffer[36].setValue(0, value); }


	public String get_HNDL_FEE_POLICY() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[37].getValue(0))); }
	public void set_HNDL_FEE_POLICY(String value) throws FMLManipulationException { this.fmlBuffer[37].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_HANDLING_FEATURE() throws FMLManipulationException { return ((String) this.fmlBuffer[38].getValue(0)); }
	public void set_HANDLING_FEATURE(String value) throws FMLManipulationException { this.fmlBuffer[38].setValue(0, value); }


	public String get_INSTALLMENT_FEATURE() throws FMLManipulationException { return ((String) this.fmlBuffer[39].getValue(0)); }
	public void set_INSTALLMENT_FEATURE(String value) throws FMLManipulationException { this.fmlBuffer[39].setValue(0, value); }


	public String get_FULL_PMNT_FEATURE() throws FMLManipulationException { return ((String) this.fmlBuffer[40].getValue(0)); }
	public void set_FULL_PMNT_FEATURE(String value) throws FMLManipulationException { this.fmlBuffer[40].setValue(0, value); }


	public String get_CRDT_FEATURE() throws FMLManipulationException { return ((String) this.fmlBuffer[41].getValue(0)); }
	public void set_CRDT_FEATURE(String value) throws FMLManipulationException { this.fmlBuffer[41].setValue(0, value); }


	public Integer get_NO_OF_INSTALLMENTS() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[42].getValue(0))); }
	public void set_NO_OF_INSTALLMENTS(Integer value) throws FMLManipulationException { this.fmlBuffer[42].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_GRACE_PERIOD() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[43].getValue(0))); }
	public void set_GRACE_PERIOD(Integer value) throws FMLManipulationException { this.fmlBuffer[43].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_EXPIRATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[44].getValue(0)); }
	public void set_EXPIRATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[44].setValue(0, value); }


	public String get_SETTLE_ON_CANCEL() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[45].getValue(0))); }
	public void set_SETTLE_ON_CANCEL(String value) throws FMLManipulationException { this.fmlBuffer[45].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_FLEX_MIN_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[46].getValue(0)); }
	public void set_FLEX_MIN_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[46].setValue(0, value); }


	public Double get_FLEX_MAX_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[47].getValue(0)); }
	public void set_FLEX_MAX_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[47].setValue(0, value); }


	public Integer get_FLEX_MIN_NO_INSTALL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[48].getValue(0))); }
	public void set_FLEX_MIN_NO_INSTALL(Integer value) throws FMLManipulationException { this.fmlBuffer[48].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_FLEX_MAX_NO_INSTALL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[49].getValue(0))); }
	public void set_FLEX_MAX_NO_INSTALL(Integer value) throws FMLManipulationException { this.fmlBuffer[49].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_LOAN_ROUND_UNIT() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[50].getValue(0))); }
	public void set_LOAN_ROUND_UNIT(Integer value) throws FMLManipulationException { this.fmlBuffer[50].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_SUB_LOAN_0VROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[51].getValue(0)); }
	public void set_SUB_LOAN_0VROWID(String value) throws FMLManipulationException { this.fmlBuffer[51].setValue(0, value); }


	public Integer get_SUB_LOAN_0VSUBSCRIBER_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[52].getValue(0)); }
	public void set_SUB_LOAN_0VSUBSCRIBER_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[52].setValue(0, value); }


	public Integer get_SUB_LOAN_0VLOAN_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[53].getValue(0)); }
	public void set_SUB_LOAN_0VLOAN_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[53].setValue(0, value); }


	public Integer get_SUB_LOAN_0VLOAN_VER_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[54].getValue(0)); }
	public void set_SUB_LOAN_0VLOAN_VER_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[54].setValue(0, value); }


	public String get_SUB_LOAN_0VSOC() throws FMLManipulationException { return ((String) this.fmlBuffer[55].getValue(0)); }
	public void set_SUB_LOAN_0VSOC(String value) throws FMLManipulationException { this.fmlBuffer[55].setValue(0, value); }


	public String get_SUB_LOAN_0VEFFECTIVE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[56].getValue(0)); }
	public void set_SUB_LOAN_0VEFFECTIVE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[56].setValue(0, value); }


	public Double get_FULL_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[57].getValue(0)); }
	public void set_FULL_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[57].setValue(0, value); }


	public Double get_CHARGED_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[58].getValue(0)); }
	public void set_CHARGED_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[58].setValue(0, value); }


	public Double get_CHARGED_FEE_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[59].getValue(0)); }
	public void set_CHARGED_FEE_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[59].setValue(0, value); }


	public Double get_UD_CHARGE_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[60].getValue(0)); }
	public void set_UD_CHARGE_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[60].setValue(0, value); }


	public Double get_UD_FEE_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[61].getValue(0)); }
	public void set_UD_FEE_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[61].setValue(0, value); }


	public Integer get_UD_NO_INSTALL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[62].getValue(0))); }
	public void set_UD_NO_INSTALL(Integer value) throws FMLManipulationException { this.fmlBuffer[62].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_UD_LAST_DATE_CRG() throws FMLManipulationException { return ((String) this.fmlBuffer[63].getValue(0)); }
	public void set_UD_LAST_DATE_CRG(String value) throws FMLManipulationException { this.fmlBuffer[63].setValue(0, value); }


	public Integer get_LAST_BILL_SEQ_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[64].getValue(0))); }
	public void set_LAST_BILL_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[64].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_LAST_DATE_OF_CRG() throws FMLManipulationException { return ((String) this.fmlBuffer[65].getValue(0)); }
	public void set_LAST_DATE_OF_CRG(String value) throws FMLManipulationException { this.fmlBuffer[65].setValue(0, value); }


	public Integer get_NO_CHARGED_INSTL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[66].getValue(0))); }
	public void set_NO_CHARGED_INSTL(Integer value) throws FMLManipulationException { this.fmlBuffer[66].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_HANDLE_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[67].getValue(0))); }
	public void set_HANDLE_IND(String value) throws FMLManipulationException { this.fmlBuffer[67].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_SUB_LOAN_0VEXPIRATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[68].getValue(0)); }
	public void set_SUB_LOAN_0VEXPIRATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[68].setValue(0, value); }


	public String get_SOURCE_MSISDN() throws FMLManipulationException { return ((String) this.fmlBuffer[69].getValue(0)); }
	public void set_SOURCE_MSISDN(String value) throws FMLManipulationException { this.fmlBuffer[69].setValue(0, value); }


	public Double get_SUB_LOAN_0VFIRST_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[70].getValue(0)); }
	public void set_SUB_LOAN_0VFIRST_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[70].setValue(0, value); }


	public Double get_SUB_LOAN_0VOTHER_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[71].getValue(0)); }
	public void set_SUB_LOAN_0VOTHER_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[71].setValue(0, value); }


	public Double get_LAST_INSTALL_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[72].getValue(0)); }
	public void set_LAST_INSTALL_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[72].setValue(0, value); }


	public Integer get_SUB_LOAN_0VNO_OF_INSTALLMENTS() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[73].getValue(0))); }
	public void set_SUB_LOAN_0VNO_OF_INSTALLMENTS(Integer value) throws FMLManipulationException { this.fmlBuffer[73].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_SOC_9VROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[74].getValue(0)); }
	public void set_SOC_9VROWID(String value) throws FMLManipulationException { this.fmlBuffer[74].setValue(0, value); }


	public String get_SOC_DESCRIPTION() throws FMLManipulationException { return ((String) this.fmlBuffer[75].getValue(0)); }
	public void set_SOC_DESCRIPTION(String value) throws FMLManipulationException { this.fmlBuffer[75].setValue(0, value); }


	public String get_ALLOW_SWITCH() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[76].getValue(0))); }
	public void set_ALLOW_SWITCH(String value) throws FMLManipulationException { this.fmlBuffer[76].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_FLEXIBLE_LOAN_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[77].getValue(0))); }
	public void set_FLEXIBLE_LOAN_IND(String value) throws FMLManipulationException { this.fmlBuffer[77].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_PCHARGERECROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[78].getValue(0)); }
	public void set_PCHARGERECROWID(String value) throws FMLManipulationException { this.fmlBuffer[78].setValue(0, value); }


	public Integer get_ROOT_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[79].getValue(0)); }
	public void set_ROOT_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[79].setValue(0, value); }


	public Integer get_PCHARGERECBAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[80].getValue(0)); }
	public void set_PCHARGERECBAN(Integer value) throws FMLManipulationException { this.fmlBuffer[80].setValue(0, value); }


	public Integer get_ACTV_BILL_SEQ_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[81].getValue(0))); }
	public void set_ACTV_BILL_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[81].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_ENT_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[82].getValue(0)); }
	public void set_ENT_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[82].setValue(0, value); }


	public Integer get_ACTV_SEQ_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[83].getValue(0))); }
	public void set_ACTV_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[83].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_SYS_CREATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[84].getValue(0)); }
	public void set_SYS_CREATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[84].setValue(0, value); }


	public String get_SYS_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[85].getValue(0)); }
	public void set_SYS_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[85].setValue(0, value); }


	public Integer get_PCHARGERECOPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[86].getValue(0)); }
	public void set_PCHARGERECOPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[86].setValue(0, value); }


	public String get_PCHARGERECAPPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[87].getValue(0)); }
	public void set_PCHARGERECAPPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[87].setValue(0, value); }


	public String get_DL_SERVICE_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[88].getValue(0)); }
	public void set_DL_SERVICE_CODE(String value) throws FMLManipulationException { this.fmlBuffer[88].setValue(0, value); }


	public Integer get_DL_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[89].getValue(0))); }
	public void set_DL_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[89].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_VOUCHER_NUM() throws FMLManipulationException { return ((String) this.fmlBuffer[90].getValue(0)); }
	public void set_VOUCHER_NUM(String value) throws FMLManipulationException { this.fmlBuffer[90].setValue(0, value); }


	public String get_PCHARGERECSUBSCRIBER_NO() throws FMLManipulationException { return ((String) this.fmlBuffer[91].getValue(0)); }
	public void set_PCHARGERECSUBSCRIBER_NO(String value) throws FMLManipulationException { this.fmlBuffer[91].setValue(0, value); }


	public String get_DEPARTMENT() throws FMLManipulationException { return ((String) this.fmlBuffer[92].getValue(0)); }
	public void set_DEPARTMENT(String value) throws FMLManipulationException { this.fmlBuffer[92].setValue(0, value); }


	public String get_ORG_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[93].getValue(0)); }
	public void set_ORG_CODE(String value) throws FMLManipulationException { this.fmlBuffer[93].setValue(0, value); }


	public String get_PRODUCT_TYPE() throws FMLManipulationException { return ((String) this.fmlBuffer[94].getValue(0)); }
	public void set_PRODUCT_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[94].setValue(0, value); }


	public String get_SUB_MARKET_CD() throws FMLManipulationException { return ((String) this.fmlBuffer[95].getValue(0)); }
	public void set_SUB_MARKET_CD(String value) throws FMLManipulationException { this.fmlBuffer[95].setValue(0, value); }


	public String get_PRIOD_CVRG_ST_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[96].getValue(0)); }
	public void set_PRIOD_CVRG_ST_DATE(String value) throws FMLManipulationException { this.fmlBuffer[96].setValue(0, value); }


	public String get_PRIOD_CVRG_ND_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[97].getValue(0)); }
	public void set_PRIOD_CVRG_ND_DATE(String value) throws FMLManipulationException { this.fmlBuffer[97].setValue(0, value); }


	public String get_CHG_CREATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[98].getValue(0)); }
	public void set_CHG_CREATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[98].setValue(0, value); }


	public String get_PCHARGERECEFFECTIVE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[99].getValue(0)); }
	public void set_PCHARGERECEFFECTIVE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[99].setValue(0, value); }


	public String get_FINANCE_EFF_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[100].getValue(0)); }
	public void set_FINANCE_EFF_DATE(String value) throws FMLManipulationException { this.fmlBuffer[100].setValue(0, value); }


	public String get_LAST_RG_RC_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[101].getValue(0)); }
	public void set_LAST_RG_RC_DATE(String value) throws FMLManipulationException { this.fmlBuffer[101].setValue(0, value); }


	public String get_ACTV_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[102].getValue(0)); }
	public void set_ACTV_DATE(String value) throws FMLManipulationException { this.fmlBuffer[102].setValue(0, value); }


	public String get_ACTV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[103].getValue(0)); }
	public void set_ACTV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[103].setValue(0, value); }


	public String get_ACTV_REASON_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[104].getValue(0)); }
	public void set_ACTV_REASON_CODE(String value) throws FMLManipulationException { this.fmlBuffer[104].setValue(0, value); }


	public Double get_ACTV_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[105].getValue(0)); }
	public void set_ACTV_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[105].setValue(0, value); }


	public Double get_DURATION() throws FMLManipulationException { return ((Double) this.fmlBuffer[106].getValue(0)); }
	public void set_DURATION(Double value) throws FMLManipulationException { this.fmlBuffer[106].setValue(0, value); }


	public Integer get_NUM_OF_CALLS() throws FMLManipulationException { return ((Integer) this.fmlBuffer[107].getValue(0)); }
	public void set_NUM_OF_CALLS(Integer value) throws FMLManipulationException { this.fmlBuffer[107].setValue(0, value); }


	public String get_FEATURE_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[108].getValue(0)); }
	public void set_FEATURE_CODE(String value) throws FMLManipulationException { this.fmlBuffer[108].setValue(0, value); }


	public String get_FTR_REVENUE_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[109].getValue(0)); }
	public void set_FTR_REVENUE_CODE(String value) throws FMLManipulationException { this.fmlBuffer[109].setValue(0, value); }


	public String get_FEATURE_CATEGORY() throws FMLManipulationException { return ((String) this.fmlBuffer[110].getValue(0)); }
	public void set_FEATURE_CATEGORY(String value) throws FMLManipulationException { this.fmlBuffer[110].setValue(0, value); }


	public String get_SECONDARY_FEATURE_CD() throws FMLManipulationException { return ((String) this.fmlBuffer[111].getValue(0)); }
	public void set_SECONDARY_FEATURE_CD(String value) throws FMLManipulationException { this.fmlBuffer[111].setValue(0, value); }


	public String get_AU_RATING_SCHEME_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[112].getValue(0))); }
	public void set_AU_RATING_SCHEME_IND(String value) throws FMLManipulationException { this.fmlBuffer[112].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BALANCE_IMPACT_CODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[113].getValue(0))); }
	public void set_BALANCE_IMPACT_CODE(String value) throws FMLManipulationException { this.fmlBuffer[113].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_PCHARGERECSOC() throws FMLManipulationException { return ((String) this.fmlBuffer[114].getValue(0)); }
	public void set_PCHARGERECSOC(String value) throws FMLManipulationException { this.fmlBuffer[114].setValue(0, value); }


	public Integer get_SOC_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[115].getValue(0)); }
	public void set_SOC_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[115].setValue(0, value); }


	public Integer get_SOC_VER_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[116].getValue(0)); }
	public void set_SOC_VER_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[116].setValue(0, value); }


	public String get_SOC_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[117].getValue(0)); }
	public void set_SOC_DATE(String value) throws FMLManipulationException { this.fmlBuffer[117].setValue(0, value); }


	public String get_SERVICE_TYPE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[118].getValue(0))); }
	public void set_SERVICE_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[118].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_SERVICE_FTR_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[119].getValue(0)); }
	public void set_SERVICE_FTR_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[119].setValue(0, value); }


	public String get_TOLL_RS_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[120].getValue(0)); }
	public void set_TOLL_RS_CODE(String value) throws FMLManipulationException { this.fmlBuffer[120].setValue(0, value); }


	public String get_SOURCE_APPL_CODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[121].getValue(0))); }
	public void set_SOURCE_APPL_CODE(String value) throws FMLManipulationException { this.fmlBuffer[121].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_ASGN_TO_BILL_APPL_CD() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[122].getValue(0))); }
	public void set_ASGN_TO_BILL_APPL_CD(String value) throws FMLManipulationException { this.fmlBuffer[122].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_INV_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[123].getValue(0)); }
	public void set_INV_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[123].setValue(0, value); }


	public Double get_VAT_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[124].getValue(0)); }
	public void set_VAT_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[124].setValue(0, value); }


	public Double get_VAT_EXMP_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[125].getValue(0)); }
	public void set_VAT_EXMP_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[125].setValue(0, value); }


	public String get_TAX_CODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[126].getValue(0))); }
	public void set_TAX_CODE(String value) throws FMLManipulationException { this.fmlBuffer[126].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_VAT_PERCENT_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[127].getValue(0)); }
	public void set_VAT_PERCENT_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[127].setValue(0, value); }


	public String get_VAT_EXMP_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[128].getValue(0))); }
	public void set_VAT_EXMP_IND(String value) throws FMLManipulationException { this.fmlBuffer[128].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_RC_FTR_PRE_PROR_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[129].getValue(0)); }
	public void set_RC_FTR_PRE_PROR_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[129].setValue(0, value); }


	public Double get_BEFORE_DISCNT_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[130].getValue(0)); }
	public void set_BEFORE_DISCNT_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[130].setValue(0, value); }


	public Double get_DISCOUNT_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[131].getValue(0)); }
	public void set_DISCOUNT_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[131].setValue(0, value); }


	public Double get_DISCOUNT_PCT() throws FMLManipulationException { return ((Double) this.fmlBuffer[132].getValue(0)); }
	public void set_DISCOUNT_PCT(Double value) throws FMLManipulationException { this.fmlBuffer[132].setValue(0, value); }


	public String get_DISCOUNT_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[133].getValue(0)); }
	public void set_DISCOUNT_CODE(String value) throws FMLManipulationException { this.fmlBuffer[133].setValue(0, value); }


	public String get_CREDIT_LEVEL() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[134].getValue(0))); }
	public void set_CREDIT_LEVEL(String value) throws FMLManipulationException { this.fmlBuffer[134].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_CRG_QUANTITY() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[135].getValue(0))); }
	public void set_CRG_QUANTITY(Integer value) throws FMLManipulationException { this.fmlBuffer[135].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_AU_ISSUE_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[136].getValue(0)); }
	public void set_AU_ISSUE_CODE(String value) throws FMLManipulationException { this.fmlBuffer[136].setValue(0, value); }


	public Integer get_AU_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[137].getValue(0)); }
	public void set_AU_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[137].setValue(0, value); }


	public String get_ACTION_DIRECTION_CD() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[138].getValue(0))); }
	public void set_ACTION_DIRECTION_CD(String value) throws FMLManipulationException { this.fmlBuffer[138].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_MANUAL_OVERRIDE_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[139].getValue(0))); }
	public void set_MANUAL_OVERRIDE_IND(String value) throws FMLManipulationException { this.fmlBuffer[139].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_MEMO_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[140].getValue(0)); }
	public void set_MEMO_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[140].setValue(0, value); }


	public String get_BL_IGNORE_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[141].getValue(0))); }
	public void set_BL_IGNORE_IND(String value) throws FMLManipulationException { this.fmlBuffer[141].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_CHARGE_TYPE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[142].getValue(0))); }
	public void set_CHARGE_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[142].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_UTC_DISCOUNT_TYPE() throws FMLManipulationException { return ((String) this.fmlBuffer[143].getValue(0)); }
	public void set_UTC_DISCOUNT_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[143].setValue(0, value); }


	public Integer get_FRWD_FM_BILL_SEQ_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[144].getValue(0))); }
	public void set_FRWD_FM_BILL_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[144].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_CHG_GROUP_LEVEL() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[145].getValue(0))); }
	public void set_CHG_GROUP_LEVEL(String value) throws FMLManipulationException { this.fmlBuffer[145].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_CHG_GROUP_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[146].getValue(0)); }
	public void set_CHG_GROUP_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[146].setValue(0, value); }


	public String get_CHARGE_HIST_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[147].getValue(0))); }
	public void set_CHARGE_HIST_IND(String value) throws FMLManipulationException { this.fmlBuffer[147].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_UTC_FROM_TO_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[148].getValue(0)); }
	public void set_UTC_FROM_TO_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[148].setValue(0, value); }


	public String get_UTC_FROM_SUBSCRIBER() throws FMLManipulationException { return ((String) this.fmlBuffer[149].getValue(0)); }
	public void set_UTC_FROM_SUBSCRIBER(String value) throws FMLManipulationException { this.fmlBuffer[149].setValue(0, value); }


	public String get_BILL_PROD_GRP() throws FMLManipulationException { return ((String) this.fmlBuffer[150].getValue(0)); }
	public void set_BILL_PROD_GRP(String value) throws FMLManipulationException { this.fmlBuffer[150].setValue(0, value); }


	public String get_UTC_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[151].getValue(0))); }
	public void set_UTC_IND(String value) throws FMLManipulationException { this.fmlBuffer[151].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_ORIG_SEQ_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[152].getValue(0)); }
	public void set_ORIG_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[152].setValue(0, value); }


	public String get_CHANNEL_SEIZURE_DT() throws FMLManipulationException { return ((String) this.fmlBuffer[153].getValue(0)); }
	public void set_CHANNEL_SEIZURE_DT(String value) throws FMLManipulationException { this.fmlBuffer[153].setValue(0, value); }


	public String get_MESSAGE_SWITCH_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[154].getValue(0)); }
	public void set_MESSAGE_SWITCH_ID(String value) throws FMLManipulationException { this.fmlBuffer[154].setValue(0, value); }


	public String get_MESSAGE_IDENTIFIER() throws FMLManipulationException { return ((String) this.fmlBuffer[155].getValue(0)); }
	public void set_MESSAGE_IDENTIFIER(String value) throws FMLManipulationException { this.fmlBuffer[155].setValue(0, value); }


	public Integer get_NO_OF_INSTALL_FROM() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[156].getValue(0))); }
	public void set_NO_OF_INSTALL_FROM(Integer value) throws FMLManipulationException { this.fmlBuffer[156].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_NO_OF_INSTALL_TO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[157].getValue(0))); }
	public void set_NO_OF_INSTALL_TO(Integer value) throws FMLManipulationException { this.fmlBuffer[157].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_TOTAL_NO_OF_INSTALL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[158].getValue(0))); }
	public void set_TOTAL_NO_OF_INSTALL(Integer value) throws FMLManipulationException { this.fmlBuffer[158].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_RMS_INV_STORE_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[159].getValue(0)); }
	public void set_RMS_INV_STORE_ID(String value) throws FMLManipulationException { this.fmlBuffer[159].setValue(0, value); }


	public Integer get_RMS_INV_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[160].getValue(0)); }
	public void set_RMS_INV_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[160].setValue(0, value); }


	public Integer get_RMS_INV_LINE_SEQ() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[161].getValue(0))); }
	public void set_RMS_INV_LINE_SEQ(Integer value) throws FMLManipulationException { this.fmlBuffer[161].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_RMS_INV_SUBLN_SEQ() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[162].getValue(0))); }
	public void set_RMS_INV_SUBLN_SEQ(Integer value) throws FMLManipulationException { this.fmlBuffer[162].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_RMS_INV_ACTV_TYPE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[163].getValue(0))); }
	public void set_RMS_INV_ACTV_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[163].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BILL_COMMENT() throws FMLManipulationException { return ((String) this.fmlBuffer[164].getValue(0)); }
	public void set_BILL_COMMENT(String value) throws FMLManipulationException { this.fmlBuffer[164].setValue(0, value); }


	public Integer get_CONV_RUN_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[165].getValue(0))); }
	public void set_CONV_RUN_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[165].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_ADJ_MSG_BILL_SEQ_NO() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[166].getValue(0))); }
	public void set_ADJ_MSG_BILL_SEQ_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[166].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_DESIGNATED_INV() throws FMLManipulationException { return ((String) this.fmlBuffer[167].getValue(0)); }
	public void set_DESIGNATED_INV(String value) throws FMLManipulationException { this.fmlBuffer[167].setValue(0, value); }


	public Integer get_DESIGNATED_ITEM() throws FMLManipulationException { return ((Integer) this.fmlBuffer[168].getValue(0)); }
	public void set_DESIGNATED_ITEM(Integer value) throws FMLManipulationException { this.fmlBuffer[168].setValue(0, value); }


	public String get_BILL_RELEVANCE_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[169].getValue(0))); }
	public void set_BILL_RELEVANCE_IND(String value) throws FMLManipulationException { this.fmlBuffer[169].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_NUM_OF_DAYS_PYM_LATE() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[170].getValue(0))); }
	public void set_NUM_OF_DAYS_PYM_LATE(Integer value) throws FMLManipulationException { this.fmlBuffer[170].setValue(0, TypeConverter.integerToShort(value)); }


	public Double get_PERCENTAGE_RATE() throws FMLManipulationException { return ((Double) this.fmlBuffer[171].getValue(0)); }
	public void set_PERCENTAGE_RATE(Double value) throws FMLManipulationException { this.fmlBuffer[171].setValue(0, value); }


	public String get_BILL_NUM_FOR_LATE_PYM() throws FMLManipulationException { return ((String) this.fmlBuffer[172].getValue(0)); }
	public void set_BILL_NUM_FOR_LATE_PYM(String value) throws FMLManipulationException { this.fmlBuffer[172].setValue(0, value); }


	public Integer get_ORIG_OPER_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[173].getValue(0)); }
	public void set_ORIG_OPER_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[173].setValue(0, value); }


	public Double get_DISC_UTC_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[174].getValue(0)); }
	public void set_DISC_UTC_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[174].setValue(0, value); }


	public Double get_DISC_UTC_VAT() throws FMLManipulationException { return ((Double) this.fmlBuffer[175].getValue(0)); }
	public void set_DISC_UTC_VAT(Double value) throws FMLManipulationException { this.fmlBuffer[175].setValue(0, value); }


	public Double get_CHRG_AMT_PRD_1() throws FMLManipulationException { return ((Double) this.fmlBuffer[176].getValue(0)); }
	public void set_CHRG_AMT_PRD_1(Double value) throws FMLManipulationException { this.fmlBuffer[176].setValue(0, value); }


	public Double get_CHRG_AMT_PRD_2() throws FMLManipulationException { return ((Double) this.fmlBuffer[177].getValue(0)); }
	public void set_CHRG_AMT_PRD_2(Double value) throws FMLManipulationException { this.fmlBuffer[177].setValue(0, value); }


	public Integer get_MATCH_TIER_LEVEL() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[178].getValue(0))); }
	public void set_MATCH_TIER_LEVEL(Integer value) throws FMLManipulationException { this.fmlBuffer[178].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_TML_UTC_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[179].getValue(0))); }
	public void set_TML_UTC_IND(String value) throws FMLManipulationException { this.fmlBuffer[179].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_ACT_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[180].getValue(0)); }
	public void set_ACT_CODE(String value) throws FMLManipulationException { this.fmlBuffer[180].setValue(0, value); }


	public String get_ACT_REASON() throws FMLManipulationException { return ((String) this.fmlBuffer[181].getValue(0)); }
	public void set_ACT_REASON(String value) throws FMLManipulationException { this.fmlBuffer[181].setValue(0, value); }


	public String get_SUSP_RC_RATE_TYPE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[182].getValue(0))); }
	public void set_SUSP_RC_RATE_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[182].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_MEMO_CTN() throws FMLManipulationException { return ((String) this.fmlBuffer[183].getValue(0)); }
	public void set_MEMO_CTN(String value) throws FMLManipulationException { this.fmlBuffer[183].setValue(0, value); }


	public String get_USER_TEXT() throws FMLManipulationException { return ((String) this.fmlBuffer[184].getValue(0)); }
	public void set_USER_TEXT(String value) throws FMLManipulationException { this.fmlBuffer[184].setValue(0, value); }


	public String get_MEMO_SOURCE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[185].getValue(0))); }
	public void set_MEMO_SOURCE(String value) throws FMLManipulationException { this.fmlBuffer[185].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_PARAM_COUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[186].getValue(0)); }
	public void set_PARAM_COUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[186].setValue(0, value); }


	public String get_P1() throws FMLManipulationException { return ((String) this.fmlBuffer[187].getValue(0)); }
	public void set_P1(String value) throws FMLManipulationException { this.fmlBuffer[187].setValue(0, value); }


	public String get_P2() throws FMLManipulationException { return ((String) this.fmlBuffer[188].getValue(0)); }
	public void set_P2(String value) throws FMLManipulationException { this.fmlBuffer[188].setValue(0, value); }


	public String get_P3() throws FMLManipulationException { return ((String) this.fmlBuffer[189].getValue(0)); }
	public void set_P3(String value) throws FMLManipulationException { this.fmlBuffer[189].setValue(0, value); }


	public String get_P4() throws FMLManipulationException { return ((String) this.fmlBuffer[190].getValue(0)); }
	public void set_P4(String value) throws FMLManipulationException { this.fmlBuffer[190].setValue(0, value); }


	public String get_P5() throws FMLManipulationException { return ((String) this.fmlBuffer[191].getValue(0)); }
	public void set_P5(String value) throws FMLManipulationException { this.fmlBuffer[191].setValue(0, value); }


	public String get_P6() throws FMLManipulationException { return ((String) this.fmlBuffer[192].getValue(0)); }
	public void set_P6(String value) throws FMLManipulationException { this.fmlBuffer[192].setValue(0, value); }


	public String get_P7() throws FMLManipulationException { return ((String) this.fmlBuffer[193].getValue(0)); }
	public void set_P7(String value) throws FMLManipulationException { this.fmlBuffer[193].setValue(0, value); }


	public String get_P8() throws FMLManipulationException { return ((String) this.fmlBuffer[194].getValue(0)); }
	public void set_P8(String value) throws FMLManipulationException { this.fmlBuffer[194].setValue(0, value); }


	public String get_P9() throws FMLManipulationException { return ((String) this.fmlBuffer[195].getValue(0)); }
	public void set_P9(String value) throws FMLManipulationException { this.fmlBuffer[195].setValue(0, value); }


	public String get_P10() throws FMLManipulationException { return ((String) this.fmlBuffer[196].getValue(0)); }
	public void set_P10(String value) throws FMLManipulationException { this.fmlBuffer[196].setValue(0, value); }


	public Double get_MEMO_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[197].getValue(0)); }
	public void set_MEMO_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[197].setValue(0, value); }


	public String get_RMS_ACT_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[198].getValue(0)); }
	public void set_RMS_ACT_CODE(String value) throws FMLManipulationException { this.fmlBuffer[198].setValue(0, value); }


	public Double get_CHARGE_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[199].getValue(0)); }
	public void set_CHARGE_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[199].setValue(0, value); }


	public String get_CHARGE_AMT_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[200].getValue(0))); }
	public void set_CHARGE_AMT_IND(String value) throws FMLManipulationException { this.fmlBuffer[200].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_WAIVE_REASON() throws FMLManipulationException { return ((String) this.fmlBuffer[201].getValue(0)); }
	public void set_WAIVE_REASON(String value) throws FMLManipulationException { this.fmlBuffer[201].setValue(0, value); }


	public String get_WAIVE_IND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[202].getValue(0))); }
	public void set_WAIVE_IND(String value) throws FMLManipulationException { this.fmlBuffer[202].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_TOTAL_ADJ_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[203].getValue(0)); }
	public void set_TOTAL_ADJ_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[203].setValue(0, value); }


	public Integer get_RM_INSTALLMENTS() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[204].getValue(0))); }
	public void set_RM_INSTALLMENTS(Integer value) throws FMLManipulationException { this.fmlBuffer[204].setValue(0, TypeConverter.integerToShort(value)); }


	public Double get_VAT_TOTAL_AMT() throws FMLManipulationException { return ((Double) this.fmlBuffer[205].getValue(0)); }
	public void set_VAT_TOTAL_AMT(Double value) throws FMLManipulationException { this.fmlBuffer[205].setValue(0, value); }



} // BlRvrsLoanStlInput
