package no.netcom.ninja.core.system.tuxedo.service.parameters;

import bea.jolt.pool.Result;
import no.netcom.ninja.core.referencetables.SystemDefaultsReferenceTable;
import no.netcom.ninja.core.system.tuxedo.exception.FMLManipulationException;
import no.netcom.ninja.core.util.TypeConverter;


/**
 * @author  Ninja - Generated by Ninja tools : created on 12-12-2019 12:47:12. Fokus 310 drop 2
 */
public class CsLsOrdOutput extends ServiceOutput {
	/**
	 * Creates a new instance of CsLsOrdOutput
	 *
	 * @throws FMLManipulationException
	 */
	public CsLsOrdOutput(int nApplicationStatus) throws FMLManipulationException {
		createFmlBuffer();
		setApplicationCode(nApplicationStatus);
	}


	public CsLsOrdOutput() {}


	/**
	 * Creates a new instance of CsLsOrdOutput
	 *
	 * @param ds Output dataset from Tuxedo service.
	 * @throws FMLManipulationException
	 */
	public CsLsOrdOutput(Result ds) throws FMLManipulationException {
		createFmlBuffer();
		populateFmlBuffer(ds);
	}


	/**
	 * Populates the FML buffer.
	 *
	 * @throws FMLManipulationException
	 */
	private void createFmlBuffer() throws FMLManipulationException {

		fmlBuffer = new FmlField[38];

		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoDirective(), 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getDefaultFokusOperatorId(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, SystemDefaultsReferenceTable.getApplicationId(), 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, SystemDefaultsReferenceTable.getTuxedoTransactionMode(), 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4, SystemDefaultsReferenceTable.getDefaultMarket(), 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, SystemDefaultsReferenceTable.getFokusEnvironmentCode(), 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoSessionId(), 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoOnlineTrxNo(), 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("ROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("ROWID", FmlField.TYPE_STRING, 19, null, 17, 600);
		this.fmlBuffer[18] = new FmlField("ORDER_NUMBER", FmlField.TYPE_INTEGER, -1, null, 18, 600);
		this.fmlBuffer[19] = new FmlField("SYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 19, 600);
		this.fmlBuffer[20] = new FmlField("SYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 20, 600);
		this.fmlBuffer[21] = new FmlField("ORDHDROPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 21, 600);
		this.fmlBuffer[22] = new FmlField("ORDHDRAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 22, 600);
		this.fmlBuffer[23] = new FmlField("DL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 23, 600);
		this.fmlBuffer[24] = new FmlField("DL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 24, 600);
		this.fmlBuffer[25] = new FmlField("EXT_PARTNER_ID", FmlField.TYPE_STRING, 6, null, 25, 600);
		this.fmlBuffer[26] = new FmlField("EXT_SRC_SYSTEM_CD", FmlField.TYPE_STRING, 6, null, 26, 600);
		this.fmlBuffer[27] = new FmlField("EXTERNAL_ORDER_ID", FmlField.TYPE_STRING, 41, null, 27, 600);
		this.fmlBuffer[28] = new FmlField("EXT_LINKED_ORDER_ID", FmlField.TYPE_STRING, 41, null, 28, 600);
		this.fmlBuffer[29] = new FmlField("EXT_COMPLETE_DATE", FmlField.TYPE_STRING, 15, null, 29, 600);
		this.fmlBuffer[30] = new FmlField("ORDER_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 30, 600);
		this.fmlBuffer[31] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 31, 600);
		this.fmlBuffer[32] = new FmlField("DEALER_CODE", FmlField.TYPE_STRING, 6, null, 32, 600);
		this.fmlBuffer[33] = new FmlField("ORDER_MODE", FmlField.TYPE_BYTE, -1, null, 33, 600);
		this.fmlBuffer[34] = new FmlField("DESCRIPTION", FmlField.TYPE_STRING, 41, null, 34, 600);
		this.fmlBuffer[35] = new FmlField("ORDER_STATUS", FmlField.TYPE_BYTE, -1, null, 35, 600);
		this.fmlBuffer[36] = new FmlField("STATUS_DATE", FmlField.TYPE_STRING, 15, null, 36, 600);
		this.fmlBuffer[37] = new FmlField("ORD_REFERENCE_ID", FmlField.TYPE_STRING, 51, null, 37, 600);
	} // End of constractor

	public Integer get_GENERATION() throws FMLManipulationException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws FMLManipulationException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws FMLManipulationException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws FMLManipulationException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws FMLManipulationException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[15].setValue(0, value); }


	public Integer get_ROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[16].getValue(0)); }
	public void set_ROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[16].setValue(0, value); }


	public String get_ROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[17].getValue(nIndex)); }
	public void set_ROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[17].setValue(nIndex, value); }
	public int get_ROWID_size() throws FMLManipulationException { return (this.fmlBuffer[17].getCount()); }


	public Integer get_ORDER_NUMBER(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[18].getValue(nIndex)); }
	public void set_ORDER_NUMBER(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[18].setValue(nIndex, value); }
	public int get_ORDER_NUMBER_size() throws FMLManipulationException { return (this.fmlBuffer[18].getCount()); }


	public String get_SYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[19].getValue(nIndex)); }
	public void set_SYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[19].setValue(nIndex, value); }
	public int get_SYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[19].getCount()); }


	public String get_SYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[20].getValue(nIndex)); }
	public void set_SYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[20].setValue(nIndex, value); }
	public int get_SYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[20].getCount()); }


	public Integer get_ORDHDROPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[21].getValue(nIndex)); }
	public void set_ORDHDROPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[21].setValue(nIndex, value); }
	public int get_ORDHDROPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[21].getCount()); }


	public String get_ORDHDRAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[22].getValue(nIndex)); }
	public void set_ORDHDRAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[22].setValue(nIndex, value); }
	public int get_ORDHDRAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[22].getCount()); }


	public String get_DL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[23].getValue(nIndex)); }
	public void set_DL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[23].setValue(nIndex, value); }
	public int get_DL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[23].getCount()); }


	public Integer get_DL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[24].getValue(nIndex))); }
	public void set_DL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[24].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_DL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[24].getCount()); }


	public String get_EXT_PARTNER_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[25].getValue(nIndex)); }
	public void set_EXT_PARTNER_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[25].setValue(nIndex, value); }
	public int get_EXT_PARTNER_ID_size() throws FMLManipulationException { return (this.fmlBuffer[25].getCount()); }


	public String get_EXT_SRC_SYSTEM_CD(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[26].getValue(nIndex)); }
	public void set_EXT_SRC_SYSTEM_CD(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[26].setValue(nIndex, value); }
	public int get_EXT_SRC_SYSTEM_CD_size() throws FMLManipulationException { return (this.fmlBuffer[26].getCount()); }


	public String get_EXTERNAL_ORDER_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[27].getValue(nIndex)); }
	public void set_EXTERNAL_ORDER_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[27].setValue(nIndex, value); }
	public int get_EXTERNAL_ORDER_ID_size() throws FMLManipulationException { return (this.fmlBuffer[27].getCount()); }


	public String get_EXT_LINKED_ORDER_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[28].getValue(nIndex)); }
	public void set_EXT_LINKED_ORDER_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[28].setValue(nIndex, value); }
	public int get_EXT_LINKED_ORDER_ID_size() throws FMLManipulationException { return (this.fmlBuffer[28].getCount()); }


	public String get_EXT_COMPLETE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[29].getValue(nIndex)); }
	public void set_EXT_COMPLETE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[29].setValue(nIndex, value); }
	public int get_EXT_COMPLETE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[29].getCount()); }


	public String get_ORDER_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[30].getValue(nIndex)); }
	public void set_ORDER_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[30].setValue(nIndex, value); }
	public int get_ORDER_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[30].getCount()); }


	public Integer get_BAN(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[31].getValue(nIndex)); }
	public void set_BAN(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[31].setValue(nIndex, value); }
	public int get_BAN_size() throws FMLManipulationException { return (this.fmlBuffer[31].getCount()); }


	public String get_DEALER_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[32].getValue(nIndex)); }
	public void set_DEALER_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[32].setValue(nIndex, value); }
	public int get_DEALER_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[32].getCount()); }


	public String get_ORDER_MODE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[33].getValue(nIndex))); }
	public void set_ORDER_MODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[33].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ORDER_MODE_size() throws FMLManipulationException { return (this.fmlBuffer[33].getCount()); }


	public String get_DESCRIPTION(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[34].getValue(nIndex)); }
	public void set_DESCRIPTION(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[34].setValue(nIndex, value); }
	public int get_DESCRIPTION_size() throws FMLManipulationException { return (this.fmlBuffer[34].getCount()); }


	public String get_ORDER_STATUS(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[35].getValue(nIndex))); }
	public void set_ORDER_STATUS(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[35].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ORDER_STATUS_size() throws FMLManipulationException { return (this.fmlBuffer[35].getCount()); }


	public String get_STATUS_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[36].getValue(nIndex)); }
	public void set_STATUS_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[36].setValue(nIndex, value); }
	public int get_STATUS_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[36].getCount()); }


	public String get_ORD_REFERENCE_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[37].getValue(nIndex)); }
	public void set_ORD_REFERENCE_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[37].setValue(nIndex, value); }
	public int get_ORD_REFERENCE_ID_size() throws FMLManipulationException { return (this.fmlBuffer[37].getCount()); }



} // CsLsOrdOutput
