package no.netcom.ninja.core.system.tuxedo.service.parameters;

import no.netcom.ninja.core.referencetables.SystemDefaultsReferenceTable;
import no.netcom.ninja.core.system.tuxedo.exception.EnvironmentException;
import no.netcom.ninja.core.system.tuxedo.exception.FMLManipulationException;
import no.netcom.ninja.core.util.TypeConverter;


/**
 * @author  Ninja - Generated by Ninja tools : created on 31-01-2020 10:37:03. Fokus 315 drop 1
 */
public class CsLsBanCtnInput extends ServiceInput {
	/**
	 * Creates a new instance of CsLsBanCtnInput
	 *
	 * @throws EnvironmentException
	 * @throws FMLManipulationException
	 */
	public CsLsBanCtnInput() throws EnvironmentException, FMLManipulationException {

		fmlBuffer = new FmlField[24];

		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoDirective(), 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getDefaultFokusOperatorId(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, SystemDefaultsReferenceTable.getApplicationId(), 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, SystemDefaultsReferenceTable.getTuxedoTransactionMode(), 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4, SystemDefaultsReferenceTable.getDefaultMarket(), 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, SystemDefaultsReferenceTable.getFokusEnvironmentCode(), 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoSessionId(), 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoOnlineTrxNo(), 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("LINK_TYPE", FmlField.TYPE_BYTE, -1, null, 17, 1);
		this.fmlBuffer[18] = new FmlField("SUB_STATUS", FmlField.TYPE_BYTE, -1, null, 18, 1);
		this.fmlBuffer[19] = new FmlField("PRODUCT_TYPE", FmlField.TYPE_STRING, 4, null, 19, 1);
		this.fmlBuffer[20] = new FmlField("DEPARTMENT_CODE", FmlField.TYPE_STRING, 5, null, 20, 1);
		this.fmlBuffer[21] = new FmlField("PAGE", FmlField.TYPE_INTEGER, -1, null, 21, 1);
		this.fmlBuffer[22] = new FmlField("PAGESIZE", FmlField.TYPE_INTEGER, -1, null, 22, 1);
		this.fmlBuffer[23] = new FmlField("SPECIFICCTN", FmlField.TYPE_STRING, 21, null, 23, 1);
	} // End of constractor

	public Integer get_GENERATION() throws FMLManipulationException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws FMLManipulationException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws FMLManipulationException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws FMLManipulationException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws FMLManipulationException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[15].setValue(0, value); }


	public Integer get_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[16].getValue(0)); }
	public void set_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[16].setValue(0, value); }


	public String get_LINK_TYPE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[17].getValue(0))); }
	public void set_LINK_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[17].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_SUB_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[18].getValue(0))); }
	public void set_SUB_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[18].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_PRODUCT_TYPE() throws FMLManipulationException { return ((String) this.fmlBuffer[19].getValue(0)); }
	public void set_PRODUCT_TYPE(String value) throws FMLManipulationException { this.fmlBuffer[19].setValue(0, value); }


	public String get_DEPARTMENT_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[20].getValue(0)); }
	public void set_DEPARTMENT_CODE(String value) throws FMLManipulationException { this.fmlBuffer[20].setValue(0, value); }


	public Integer get_PAGE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[21].getValue(0)); }
	public void set_PAGE(Integer value) throws FMLManipulationException { this.fmlBuffer[21].setValue(0, value); }


	public Integer get_PAGESIZE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[22].getValue(0)); }
	public void set_PAGESIZE(Integer value) throws FMLManipulationException { this.fmlBuffer[22].setValue(0, value); }


	public String get_SPECIFICCTN() throws FMLManipulationException { return ((String) this.fmlBuffer[23].getValue(0)); }
	public void set_SPECIFICCTN(String value) throws FMLManipulationException { this.fmlBuffer[23].setValue(0, value); }



} // CsLsBanCtnInput
