package no.netcom.ninja.core.system.tuxedo.service.parameters;

import no.netcom.ninja.core.referencetables.SystemDefaultsReferenceTable;
import no.netcom.ninja.core.system.tuxedo.exception.EnvironmentException;
import no.netcom.ninja.core.system.tuxedo.exception.FMLManipulationException;
import no.netcom.ninja.core.util.TypeConverter;


/**
 * @author  Ninja - Generated by Ninja tools : created on 08-10-2019 10:40:24. Fokus 310 drop 1
 */
public class ArSvBilPrmInput extends ServiceInput {
	/**
	 * Creates a new instance of ArSvBilPrmInput
	 *
	 * @throws EnvironmentException
	 * @throws FMLManipulationException
	 */
	public ArSvBilPrmInput() throws EnvironmentException, FMLManipulationException {

		fmlBuffer = new FmlField[152];

		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoDirective(), 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getDefaultFokusOperatorId(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, SystemDefaultsReferenceTable.getApplicationId(), 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, SystemDefaultsReferenceTable.getTuxedoTransactionMode(), 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4, SystemDefaultsReferenceTable.getDefaultMarket(), 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, SystemDefaultsReferenceTable.getFokusEnvironmentCode(), 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoSessionId(), 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoOnlineTrxNo(), 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("CUSTOMERID", FmlField.TYPE_INTEGER, -1, null, 17, 1);
		this.fmlBuffer[18] = new FmlField("BLDEFMAILIND", FmlField.TYPE_BYTE, -1, null, 18, 1);
		this.fmlBuffer[19] = new FmlField("NOOFCOPIES", FmlField.TYPE_SHORT, -1, null, 19, 1);
		this.fmlBuffer[20] = new FmlField("FORMAT", FmlField.TYPE_STRING, 3, null, 20, 1);
		this.fmlBuffer[21] = new FmlField("MEDIA", FmlField.TYPE_STRING, 3, null, 21, 1);
		this.fmlBuffer[22] = new FmlField("PRINTCATEGORY", FmlField.TYPE_STRING, 3, null, 22, 1);
		this.fmlBuffer[23] = new FmlField("ROW_COUNT", FmlField.TYPE_INTEGER, -1, null, 23, 1);
		this.fmlBuffer[24] = new FmlField("ACT_CODE", FmlField.TYPE_STRING, 4, null, 24, 50);
		this.fmlBuffer[25] = new FmlField("ACT_REASON", FmlField.TYPE_STRING, 5, null, 25, 50);
		this.fmlBuffer[26] = new FmlField("SUSP_RC_RATE_TYPE", FmlField.TYPE_BYTE, -1, null, 26, 50);
		this.fmlBuffer[27] = new FmlField("MEMO_CTN", FmlField.TYPE_STRING, 21, null, 27, 50);
		this.fmlBuffer[28] = new FmlField("USER_TEXT", FmlField.TYPE_STRING, 2001, null, 28, 50);
		this.fmlBuffer[29] = new FmlField("MEMO_SOURCE", FmlField.TYPE_BYTE, -1, null, 29, 50);
		this.fmlBuffer[30] = new FmlField("PARAM_COUNT", FmlField.TYPE_INTEGER, -1, null, 30, 50);
		this.fmlBuffer[31] = new FmlField("P1", FmlField.TYPE_STRING, 51, null, 31, 50);
		this.fmlBuffer[32] = new FmlField("P2", FmlField.TYPE_STRING, 51, null, 32, 50);
		this.fmlBuffer[33] = new FmlField("P3", FmlField.TYPE_STRING, 51, null, 33, 50);
		this.fmlBuffer[34] = new FmlField("P4", FmlField.TYPE_STRING, 51, null, 34, 50);
		this.fmlBuffer[35] = new FmlField("P5", FmlField.TYPE_STRING, 51, null, 35, 50);
		this.fmlBuffer[36] = new FmlField("P6", FmlField.TYPE_STRING, 51, null, 36, 50);
		this.fmlBuffer[37] = new FmlField("P7", FmlField.TYPE_STRING, 51, null, 37, 50);
		this.fmlBuffer[38] = new FmlField("P8", FmlField.TYPE_STRING, 51, null, 38, 50);
		this.fmlBuffer[39] = new FmlField("P9", FmlField.TYPE_STRING, 51, null, 39, 50);
		this.fmlBuffer[40] = new FmlField("P10", FmlField.TYPE_STRING, 51, null, 40, 50);
		this.fmlBuffer[41] = new FmlField("MEMO_AMT", FmlField.TYPE_DOUBLE, -1, null, 41, 50);
		this.fmlBuffer[42] = new FmlField("RMS_ACT_CODE", FmlField.TYPE_STRING, 5, null, 42, 50);
		this.fmlBuffer[43] = new FmlField("CHARGE_AMT", FmlField.TYPE_DOUBLE, -1, null, 43, 50);
		this.fmlBuffer[44] = new FmlField("CHARGE_AMT_IND", FmlField.TYPE_BYTE, -1, null, 44, 50);
		this.fmlBuffer[45] = new FmlField("WAIVE_REASON", FmlField.TYPE_STRING, 7, null, 45, 50);
		this.fmlBuffer[46] = new FmlField("WAIVE_IND", FmlField.TYPE_BYTE, -1, null, 46, 50);
		this.fmlBuffer[47] = new FmlField("ROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 47, 1);
		this.fmlBuffer[48] = new FmlField("LINK_MODE", FmlField.TYPE_BYTE, -1, null, 48, 20);
		this.fmlBuffer[49] = new FmlField("LINK_BAN", FmlField.TYPE_INTEGER, -1, null, 49, 20);
		this.fmlBuffer[50] = new FmlField("LINK_SUBSCRIBER", FmlField.TYPE_STRING, 21, null, 50, 20);
		this.fmlBuffer[51] = new FmlField("LINK_ROW_ID", FmlField.TYPE_STRING, 19, null, 51, 20);
		this.fmlBuffer[52] = new FmlField("LINK_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 52, 20);
		this.fmlBuffer[53] = new FmlField("CUSTOMER_ID", FmlField.TYPE_INTEGER, -1, null, 53, 20);
		this.fmlBuffer[54] = new FmlField("LNKRECBAN", FmlField.TYPE_INTEGER, -1, null, 54, 20);
		this.fmlBuffer[55] = new FmlField("SUBSCRIBER_NO", FmlField.TYPE_STRING, 21, null, 55, 20);
		this.fmlBuffer[56] = new FmlField("LINK_TYPE", FmlField.TYPE_BYTE, -1, null, 56, 20);
		this.fmlBuffer[57] = new FmlField("EFFECTIVE_DATE", FmlField.TYPE_STRING, 9, null, 57, 20);
		this.fmlBuffer[58] = new FmlField("FOREIGN_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 58, 20);
		this.fmlBuffer[59] = new FmlField("BILLING_IND", FmlField.TYPE_BYTE, -1, null, 59, 20);
		this.fmlBuffer[60] = new FmlField("MAILING_IND", FmlField.TYPE_BYTE, -1, null, 60, 20);
		this.fmlBuffer[61] = new FmlField("USER_IND", FmlField.TYPE_BYTE, -1, null, 61, 20);
		this.fmlBuffer[62] = new FmlField("LINK_BILLING_IND", FmlField.TYPE_BYTE, -1, null, 62, 20);
		this.fmlBuffer[63] = new FmlField("LINK_MAILING_IND", FmlField.TYPE_BYTE, -1, null, 63, 20);
		this.fmlBuffer[64] = new FmlField("LINK_USER_IND", FmlField.TYPE_BYTE, -1, null, 64, 20);
		this.fmlBuffer[65] = new FmlField("NM_MODE", FmlField.TYPE_BYTE, -1, null, 65, 20);
		this.fmlBuffer[66] = new FmlField("NM_UP_TYPE", FmlField.TYPE_BYTE, -1, null, 66, 20);
		this.fmlBuffer[67] = new FmlField("NM_EXPIRE_DATE", FmlField.TYPE_STRING, 9, null, 67, 20);
		this.fmlBuffer[68] = new FmlField("ROWID", FmlField.TYPE_STRING, 19, null, 68, 20);
		this.fmlBuffer[69] = new FmlField("NAME_ID", FmlField.TYPE_INTEGER, -1, null, 69, 20);
		this.fmlBuffer[70] = new FmlField("SYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 70, 20);
		this.fmlBuffer[71] = new FmlField("SYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 71, 20);
		this.fmlBuffer[72] = new FmlField("NAMERECOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 72, 20);
		this.fmlBuffer[73] = new FmlField("NAMERECAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 73, 20);
		this.fmlBuffer[74] = new FmlField("DL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 74, 20);
		this.fmlBuffer[75] = new FmlField("DL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 75, 20);
		this.fmlBuffer[76] = new FmlField("CONTROL_NAME", FmlField.TYPE_STRING, 41, null, 76, 20);
		this.fmlBuffer[77] = new FmlField("LAST_BUSINESS_NAME", FmlField.TYPE_STRING, 61, null, 77, 20);
		this.fmlBuffer[78] = new FmlField("FIRST_NAME", FmlField.TYPE_STRING, 33, null, 78, 20);
		this.fmlBuffer[79] = new FmlField("ADDITIONAL_TITLE", FmlField.TYPE_STRING, 61, null, 79, 20);
		this.fmlBuffer[80] = new FmlField("NAME_FORMAT", FmlField.TYPE_BYTE, -1, null, 80, 20);
		this.fmlBuffer[81] = new FmlField("BIRTH_DATE", FmlField.TYPE_STRING, 9, null, 81, 20);
		this.fmlBuffer[82] = new FmlField("IDENTIFY", FmlField.TYPE_STRING, 21, null, 82, 20);
		this.fmlBuffer[83] = new FmlField("ID_TYPE", FmlField.TYPE_STRING, 5, null, 83, 20);
		this.fmlBuffer[84] = new FmlField("COMP_REG_ID", FmlField.TYPE_STRING, 51, null, 84, 20);
		this.fmlBuffer[85] = new FmlField("KOB", FmlField.TYPE_DOUBLE, -1, null, 85, 20);
		this.fmlBuffer[86] = new FmlField("MIDDLE_INITIAL", FmlField.TYPE_STRING, 33, null, 86, 20);
		this.fmlBuffer[87] = new FmlField("TELEMARKET_ID", FmlField.TYPE_STRING, 11, null, 87, 20);
		this.fmlBuffer[88] = new FmlField("CONV_RUN_NO", FmlField.TYPE_SHORT, -1, null, 88, 20);
		this.fmlBuffer[89] = new FmlField("NAME_TITLE_SALUTATION", FmlField.TYPE_STRING, 21, null, 89, 20);
		this.fmlBuffer[90] = new FmlField("NATIONALITY_CD", FmlField.TYPE_STRING, 4, null, 90, 20);
		this.fmlBuffer[91] = new FmlField("GENDER", FmlField.TYPE_BYTE, -1, null, 91, 20);
		this.fmlBuffer[92] = new FmlField("MARITAL_STATUS", FmlField.TYPE_STRING, 5, null, 92, 20);
		this.fmlBuffer[93] = new FmlField("ROLE_IND", FmlField.TYPE_BYTE, -1, null, 93, 20);
		this.fmlBuffer[94] = new FmlField("ADR_MODE", FmlField.TYPE_BYTE, -1, null, 94, 20);
		this.fmlBuffer[95] = new FmlField("ADR_UP_TYPE", FmlField.TYPE_BYTE, -1, null, 95, 20);
		this.fmlBuffer[96] = new FmlField("ADR_EXPIRE_DATE", FmlField.TYPE_STRING, 9, null, 96, 20);
		this.fmlBuffer[97] = new FmlField("ADDRESSRECROWID", FmlField.TYPE_STRING, 19, null, 97, 20);
		this.fmlBuffer[98] = new FmlField("ADDRESS_ID", FmlField.TYPE_INTEGER, -1, null, 98, 20);
		this.fmlBuffer[99] = new FmlField("ADDRESSRECSYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 99, 20);
		this.fmlBuffer[100] = new FmlField("ADDRESSRECSYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 100, 20);
		this.fmlBuffer[101] = new FmlField("ADDRESSRECOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 101, 20);
		this.fmlBuffer[102] = new FmlField("ADDRESSRECAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 102, 20);
		this.fmlBuffer[103] = new FmlField("ADDRESSRECDL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 103, 20);
		this.fmlBuffer[104] = new FmlField("ADDRESSRECDL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 104, 20);
		this.fmlBuffer[105] = new FmlField("ADR_TYPE", FmlField.TYPE_BYTE, -1, null, 105, 20);
		this.fmlBuffer[106] = new FmlField("ADR_STATUS", FmlField.TYPE_BYTE, -1, null, 106, 20);
		this.fmlBuffer[107] = new FmlField("ADR_STATUS_DATE", FmlField.TYPE_STRING, 9, null, 107, 20);
		this.fmlBuffer[108] = new FmlField("ADR_SECONDARY_LN", FmlField.TYPE_STRING, 101, null, 108, 20);
		this.fmlBuffer[109] = new FmlField("ADR_PRIMARY_LN", FmlField.TYPE_STRING, 101, null, 109, 20);
		this.fmlBuffer[110] = new FmlField("ADR_CITY", FmlField.TYPE_STRING, 40, null, 110, 20);
		this.fmlBuffer[111] = new FmlField("ADR_ZIP", FmlField.TYPE_STRING, 10, null, 111, 20);
		this.fmlBuffer[112] = new FmlField("ADR_HOUSE_NO", FmlField.TYPE_STRING, 21, null, 112, 20);
		this.fmlBuffer[113] = new FmlField("ADR_STREET_NAME", FmlField.TYPE_STRING, 61, null, 113, 20);
		this.fmlBuffer[114] = new FmlField("ADR_DIRECTION", FmlField.TYPE_STRING, 3, null, 114, 20);
		this.fmlBuffer[115] = new FmlField("ADR_POB", FmlField.TYPE_STRING, 11, null, 115, 20);
		this.fmlBuffer[116] = new FmlField("ADR_COUNTRY", FmlField.TYPE_STRING, 4, null, 116, 20);
		this.fmlBuffer[117] = new FmlField("ADR_HOUSE_LETTER", FmlField.TYPE_STRING, 3, null, 117, 20);
		this.fmlBuffer[118] = new FmlField("ADR_STORY", FmlField.TYPE_STRING, 3, null, 118, 20);
		this.fmlBuffer[119] = new FmlField("ADR_DOOR_NO", FmlField.TYPE_STRING, 5, null, 119, 20);
		this.fmlBuffer[120] = new FmlField("ADR_EMAIL", FmlField.TYPE_STRING, 151, null, 120, 20);
		this.fmlBuffer[121] = new FmlField("SINCE_DATE", FmlField.TYPE_STRING, 9, null, 121, 20);
		this.fmlBuffer[122] = new FmlField("ADR_DISTRICT", FmlField.TYPE_STRING, 41, null, 122, 20);
		this.fmlBuffer[123] = new FmlField("CO_IND", FmlField.TYPE_BYTE, -1, null, 123, 20);
		this.fmlBuffer[124] = new FmlField("ADDRESSRECCONV_RUN_NO", FmlField.TYPE_SHORT, -1, null, 124, 20);
		this.fmlBuffer[125] = new FmlField("ACCOMMODATION_TYPE", FmlField.TYPE_STRING, 5, null, 125, 20);
		this.fmlBuffer[126] = new FmlField("COUNTY_CODE", FmlField.TYPE_STRING, 3, null, 126, 20);
		this.fmlBuffer[127] = new FmlField("COMMUNITY_NAME", FmlField.TYPE_STRING, 31, null, 127, 20);
		this.fmlBuffer[128] = new FmlField("ADR_CO_NAME", FmlField.TYPE_STRING, 61, null, 128, 20);
		this.fmlBuffer[129] = new FmlField("ADR_HOUSE_NAME", FmlField.TYPE_STRING, 61, null, 129, 20);
		this.fmlBuffer[130] = new FmlField("ADR_P1", FmlField.TYPE_STRING, 61, null, 130, 20);
		this.fmlBuffer[131] = new FmlField("ADR_P2", FmlField.TYPE_STRING, 61, null, 131, 20);
		this.fmlBuffer[132] = new FmlField("ADR_P3", FmlField.TYPE_STRING, 61, null, 132, 20);
		this.fmlBuffer[133] = new FmlField("ADR_P4", FmlField.TYPE_STRING, 61, null, 133, 20);
		this.fmlBuffer[134] = new FmlField("ADR_P5", FmlField.TYPE_STRING, 61, null, 134, 20);
		this.fmlBuffer[135] = new FmlField("ADR_P6", FmlField.TYPE_STRING, 61, null, 135, 20);
		this.fmlBuffer[136] = new FmlField("ADR_P7", FmlField.TYPE_STRING, 61, null, 136, 20);
		this.fmlBuffer[137] = new FmlField("ADR_P8", FmlField.TYPE_STRING, 61, null, 137, 20);
		this.fmlBuffer[138] = new FmlField("ADR_P9", FmlField.TYPE_STRING, 61, null, 138, 20);
		this.fmlBuffer[139] = new FmlField("ADR_P10", FmlField.TYPE_STRING, 61, null, 139, 20);
		this.fmlBuffer[140] = new FmlField("PSVBLPRMBUFROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 140, 1);
		this.fmlBuffer[141] = new FmlField("BPMODE", FmlField.TYPE_BYTE, -1, null, 141, 20);
		this.fmlBuffer[142] = new FmlField("BPSEQNO", FmlField.TYPE_INTEGER, -1, null, 142, 20);
		this.fmlBuffer[143] = new FmlField("BPEFFDATE", FmlField.TYPE_STRING, 9, null, 143, 20);
		this.fmlBuffer[144] = new FmlField("BPEXPDATE", FmlField.TYPE_STRING, 9, null, 144, 20);
		this.fmlBuffer[145] = new FmlField("BPFORMAT", FmlField.TYPE_STRING, 3, null, 145, 20);
		this.fmlBuffer[146] = new FmlField("BPMEDIA", FmlField.TYPE_STRING, 3, null, 146, 20);
		this.fmlBuffer[147] = new FmlField("BPPRINTCATEGORY", FmlField.TYPE_STRING, 3, null, 147, 20);
		this.fmlBuffer[148] = new FmlField("BPNOOFCOPIES", FmlField.TYPE_SHORT, -1, null, 148, 20);
		this.fmlBuffer[149] = new FmlField("BP_LANGUAGE", FmlField.TYPE_STRING, 3, null, 149, 20);
		this.fmlBuffer[150] = new FmlField("BP_CALL_DETAILS_MEDIA", FmlField.TYPE_BYTE, -1, null, 150, 20);
		this.fmlBuffer[151] = new FmlField("BP_REFERENCE_INFO", FmlField.TYPE_STRING, 31, null, 151, 20);
	} // End of constractor

	public Integer get_GENERATION() throws FMLManipulationException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws FMLManipulationException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws FMLManipulationException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws FMLManipulationException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws FMLManipulationException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[15].setValue(0, value); }


	public Integer get_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[16].getValue(0)); }
	public void set_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[16].setValue(0, value); }


	public Integer get_CUSTOMERID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[17].getValue(0)); }
	public void set_CUSTOMERID(Integer value) throws FMLManipulationException { this.fmlBuffer[17].setValue(0, value); }


	public String get_BLDEFMAILIND() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[18].getValue(0))); }
	public void set_BLDEFMAILIND(String value) throws FMLManipulationException { this.fmlBuffer[18].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_NOOFCOPIES() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[19].getValue(0))); }
	public void set_NOOFCOPIES(Integer value) throws FMLManipulationException { this.fmlBuffer[19].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_FORMAT() throws FMLManipulationException { return ((String) this.fmlBuffer[20].getValue(0)); }
	public void set_FORMAT(String value) throws FMLManipulationException { this.fmlBuffer[20].setValue(0, value); }


	public String get_MEDIA() throws FMLManipulationException { return ((String) this.fmlBuffer[21].getValue(0)); }
	public void set_MEDIA(String value) throws FMLManipulationException { this.fmlBuffer[21].setValue(0, value); }


	public String get_PRINTCATEGORY() throws FMLManipulationException { return ((String) this.fmlBuffer[22].getValue(0)); }
	public void set_PRINTCATEGORY(String value) throws FMLManipulationException { this.fmlBuffer[22].setValue(0, value); }


	public Integer get_ROW_COUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[23].getValue(0)); }
	public void set_ROW_COUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[23].setValue(0, value); }


	public String get_ACT_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[24].getValue(nIndex)); }
	public void set_ACT_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[24].setValue(nIndex, value); }
	public int get_ACT_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[24].getCount()); }


	public String get_ACT_REASON(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[25].getValue(nIndex)); }
	public void set_ACT_REASON(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[25].setValue(nIndex, value); }
	public int get_ACT_REASON_size() throws FMLManipulationException { return (this.fmlBuffer[25].getCount()); }


	public String get_SUSP_RC_RATE_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[26].getValue(nIndex))); }
	public void set_SUSP_RC_RATE_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[26].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_SUSP_RC_RATE_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[26].getCount()); }


	public String get_MEMO_CTN(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[27].getValue(nIndex)); }
	public void set_MEMO_CTN(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[27].setValue(nIndex, value); }
	public int get_MEMO_CTN_size() throws FMLManipulationException { return (this.fmlBuffer[27].getCount()); }


	public String get_USER_TEXT(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[28].getValue(nIndex)); }
	public void set_USER_TEXT(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[28].setValue(nIndex, value); }
	public int get_USER_TEXT_size() throws FMLManipulationException { return (this.fmlBuffer[28].getCount()); }


	public String get_MEMO_SOURCE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[29].getValue(nIndex))); }
	public void set_MEMO_SOURCE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[29].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_MEMO_SOURCE_size() throws FMLManipulationException { return (this.fmlBuffer[29].getCount()); }


	public Integer get_PARAM_COUNT(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[30].getValue(nIndex)); }
	public void set_PARAM_COUNT(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[30].setValue(nIndex, value); }
	public int get_PARAM_COUNT_size() throws FMLManipulationException { return (this.fmlBuffer[30].getCount()); }


	public String get_P1(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[31].getValue(nIndex)); }
	public void set_P1(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[31].setValue(nIndex, value); }
	public int get_P1_size() throws FMLManipulationException { return (this.fmlBuffer[31].getCount()); }


	public String get_P2(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[32].getValue(nIndex)); }
	public void set_P2(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[32].setValue(nIndex, value); }
	public int get_P2_size() throws FMLManipulationException { return (this.fmlBuffer[32].getCount()); }


	public String get_P3(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[33].getValue(nIndex)); }
	public void set_P3(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[33].setValue(nIndex, value); }
	public int get_P3_size() throws FMLManipulationException { return (this.fmlBuffer[33].getCount()); }


	public String get_P4(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[34].getValue(nIndex)); }
	public void set_P4(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[34].setValue(nIndex, value); }
	public int get_P4_size() throws FMLManipulationException { return (this.fmlBuffer[34].getCount()); }


	public String get_P5(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[35].getValue(nIndex)); }
	public void set_P5(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[35].setValue(nIndex, value); }
	public int get_P5_size() throws FMLManipulationException { return (this.fmlBuffer[35].getCount()); }


	public String get_P6(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[36].getValue(nIndex)); }
	public void set_P6(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[36].setValue(nIndex, value); }
	public int get_P6_size() throws FMLManipulationException { return (this.fmlBuffer[36].getCount()); }


	public String get_P7(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[37].getValue(nIndex)); }
	public void set_P7(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[37].setValue(nIndex, value); }
	public int get_P7_size() throws FMLManipulationException { return (this.fmlBuffer[37].getCount()); }


	public String get_P8(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[38].getValue(nIndex)); }
	public void set_P8(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[38].setValue(nIndex, value); }
	public int get_P8_size() throws FMLManipulationException { return (this.fmlBuffer[38].getCount()); }


	public String get_P9(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[39].getValue(nIndex)); }
	public void set_P9(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[39].setValue(nIndex, value); }
	public int get_P9_size() throws FMLManipulationException { return (this.fmlBuffer[39].getCount()); }


	public String get_P10(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[40].getValue(nIndex)); }
	public void set_P10(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[40].setValue(nIndex, value); }
	public int get_P10_size() throws FMLManipulationException { return (this.fmlBuffer[40].getCount()); }


	public Double get_MEMO_AMT(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[41].getValue(nIndex)); }
	public void set_MEMO_AMT(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[41].setValue(nIndex, value); }
	public int get_MEMO_AMT_size() throws FMLManipulationException { return (this.fmlBuffer[41].getCount()); }


	public String get_RMS_ACT_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[42].getValue(nIndex)); }
	public void set_RMS_ACT_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[42].setValue(nIndex, value); }
	public int get_RMS_ACT_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[42].getCount()); }


	public Double get_CHARGE_AMT(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[43].getValue(nIndex)); }
	public void set_CHARGE_AMT(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[43].setValue(nIndex, value); }
	public int get_CHARGE_AMT_size() throws FMLManipulationException { return (this.fmlBuffer[43].getCount()); }


	public String get_CHARGE_AMT_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[44].getValue(nIndex))); }
	public void set_CHARGE_AMT_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[44].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_CHARGE_AMT_IND_size() throws FMLManipulationException { return (this.fmlBuffer[44].getCount()); }


	public String get_WAIVE_REASON(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[45].getValue(nIndex)); }
	public void set_WAIVE_REASON(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[45].setValue(nIndex, value); }
	public int get_WAIVE_REASON_size() throws FMLManipulationException { return (this.fmlBuffer[45].getCount()); }


	public String get_WAIVE_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[46].getValue(nIndex))); }
	public void set_WAIVE_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[46].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_WAIVE_IND_size() throws FMLManipulationException { return (this.fmlBuffer[46].getCount()); }


	public Integer get_ROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[47].getValue(0)); }
	public void set_ROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[47].setValue(0, value); }


	public String get_LINK_MODE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[48].getValue(nIndex))); }
	public void set_LINK_MODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[48].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_LINK_MODE_size() throws FMLManipulationException { return (this.fmlBuffer[48].getCount()); }


	public Integer get_LINK_BAN(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[49].getValue(nIndex)); }
	public void set_LINK_BAN(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[49].setValue(nIndex, value); }
	public int get_LINK_BAN_size() throws FMLManipulationException { return (this.fmlBuffer[49].getCount()); }


	public String get_LINK_SUBSCRIBER(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[50].getValue(nIndex)); }
	public void set_LINK_SUBSCRIBER(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[50].setValue(nIndex, value); }
	public int get_LINK_SUBSCRIBER_size() throws FMLManipulationException { return (this.fmlBuffer[50].getCount()); }


	public String get_LINK_ROW_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[51].getValue(nIndex)); }
	public void set_LINK_ROW_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[51].setValue(nIndex, value); }
	public int get_LINK_ROW_ID_size() throws FMLManipulationException { return (this.fmlBuffer[51].getCount()); }


	public Integer get_LINK_SEQ_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[52].getValue(nIndex)); }
	public void set_LINK_SEQ_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[52].setValue(nIndex, value); }
	public int get_LINK_SEQ_NO_size() throws FMLManipulationException { return (this.fmlBuffer[52].getCount()); }


	public Integer get_CUSTOMER_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[53].getValue(nIndex)); }
	public void set_CUSTOMER_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[53].setValue(nIndex, value); }
	public int get_CUSTOMER_ID_size() throws FMLManipulationException { return (this.fmlBuffer[53].getCount()); }


	public Integer get_LNKRECBAN(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[54].getValue(nIndex)); }
	public void set_LNKRECBAN(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[54].setValue(nIndex, value); }
	public int get_LNKRECBAN_size() throws FMLManipulationException { return (this.fmlBuffer[54].getCount()); }


	public String get_SUBSCRIBER_NO(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[55].getValue(nIndex)); }
	public void set_SUBSCRIBER_NO(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[55].setValue(nIndex, value); }
	public int get_SUBSCRIBER_NO_size() throws FMLManipulationException { return (this.fmlBuffer[55].getCount()); }


	public String get_LINK_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[56].getValue(nIndex))); }
	public void set_LINK_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[56].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_LINK_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[56].getCount()); }


	public String get_EFFECTIVE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[57].getValue(nIndex)); }
	public void set_EFFECTIVE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[57].setValue(nIndex, value); }
	public int get_EFFECTIVE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[57].getCount()); }


	public Integer get_FOREIGN_SEQ_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[58].getValue(nIndex)); }
	public void set_FOREIGN_SEQ_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[58].setValue(nIndex, value); }
	public int get_FOREIGN_SEQ_NO_size() throws FMLManipulationException { return (this.fmlBuffer[58].getCount()); }


	public String get_BILLING_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[59].getValue(nIndex))); }
	public void set_BILLING_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[59].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_BILLING_IND_size() throws FMLManipulationException { return (this.fmlBuffer[59].getCount()); }


	public String get_MAILING_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[60].getValue(nIndex))); }
	public void set_MAILING_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[60].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_MAILING_IND_size() throws FMLManipulationException { return (this.fmlBuffer[60].getCount()); }


	public String get_USER_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[61].getValue(nIndex))); }
	public void set_USER_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[61].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_USER_IND_size() throws FMLManipulationException { return (this.fmlBuffer[61].getCount()); }


	public String get_LINK_BILLING_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[62].getValue(nIndex))); }
	public void set_LINK_BILLING_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[62].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_LINK_BILLING_IND_size() throws FMLManipulationException { return (this.fmlBuffer[62].getCount()); }


	public String get_LINK_MAILING_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[63].getValue(nIndex))); }
	public void set_LINK_MAILING_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[63].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_LINK_MAILING_IND_size() throws FMLManipulationException { return (this.fmlBuffer[63].getCount()); }


	public String get_LINK_USER_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[64].getValue(nIndex))); }
	public void set_LINK_USER_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[64].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_LINK_USER_IND_size() throws FMLManipulationException { return (this.fmlBuffer[64].getCount()); }


	public String get_NM_MODE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[65].getValue(nIndex))); }
	public void set_NM_MODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[65].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_NM_MODE_size() throws FMLManipulationException { return (this.fmlBuffer[65].getCount()); }


	public String get_NM_UP_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[66].getValue(nIndex))); }
	public void set_NM_UP_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[66].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_NM_UP_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[66].getCount()); }


	public String get_NM_EXPIRE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[67].getValue(nIndex)); }
	public void set_NM_EXPIRE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[67].setValue(nIndex, value); }
	public int get_NM_EXPIRE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[67].getCount()); }


	public String get_ROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[68].getValue(nIndex)); }
	public void set_ROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[68].setValue(nIndex, value); }
	public int get_ROWID_size() throws FMLManipulationException { return (this.fmlBuffer[68].getCount()); }


	public Integer get_NAME_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[69].getValue(nIndex)); }
	public void set_NAME_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[69].setValue(nIndex, value); }
	public int get_NAME_ID_size() throws FMLManipulationException { return (this.fmlBuffer[69].getCount()); }


	public String get_SYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[70].getValue(nIndex)); }
	public void set_SYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[70].setValue(nIndex, value); }
	public int get_SYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[70].getCount()); }


	public String get_SYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[71].getValue(nIndex)); }
	public void set_SYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[71].setValue(nIndex, value); }
	public int get_SYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[71].getCount()); }


	public Integer get_NAMERECOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[72].getValue(nIndex)); }
	public void set_NAMERECOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[72].setValue(nIndex, value); }
	public int get_NAMERECOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[72].getCount()); }


	public String get_NAMERECAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[73].getValue(nIndex)); }
	public void set_NAMERECAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[73].setValue(nIndex, value); }
	public int get_NAMERECAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[73].getCount()); }


	public String get_DL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[74].getValue(nIndex)); }
	public void set_DL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[74].setValue(nIndex, value); }
	public int get_DL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[74].getCount()); }


	public Integer get_DL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[75].getValue(nIndex))); }
	public void set_DL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[75].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_DL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[75].getCount()); }


	public String get_CONTROL_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[76].getValue(nIndex)); }
	public void set_CONTROL_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[76].setValue(nIndex, value); }
	public int get_CONTROL_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[76].getCount()); }


	public String get_LAST_BUSINESS_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[77].getValue(nIndex)); }
	public void set_LAST_BUSINESS_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[77].setValue(nIndex, value); }
	public int get_LAST_BUSINESS_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[77].getCount()); }


	public String get_FIRST_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[78].getValue(nIndex)); }
	public void set_FIRST_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[78].setValue(nIndex, value); }
	public int get_FIRST_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[78].getCount()); }


	public String get_ADDITIONAL_TITLE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[79].getValue(nIndex)); }
	public void set_ADDITIONAL_TITLE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[79].setValue(nIndex, value); }
	public int get_ADDITIONAL_TITLE_size() throws FMLManipulationException { return (this.fmlBuffer[79].getCount()); }


	public String get_NAME_FORMAT(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[80].getValue(nIndex))); }
	public void set_NAME_FORMAT(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[80].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_NAME_FORMAT_size() throws FMLManipulationException { return (this.fmlBuffer[80].getCount()); }


	public String get_BIRTH_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[81].getValue(nIndex)); }
	public void set_BIRTH_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[81].setValue(nIndex, value); }
	public int get_BIRTH_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[81].getCount()); }


	public String get_IDENTIFY(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[82].getValue(nIndex)); }
	public void set_IDENTIFY(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[82].setValue(nIndex, value); }
	public int get_IDENTIFY_size() throws FMLManipulationException { return (this.fmlBuffer[82].getCount()); }


	public String get_ID_TYPE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[83].getValue(nIndex)); }
	public void set_ID_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[83].setValue(nIndex, value); }
	public int get_ID_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[83].getCount()); }


	public String get_COMP_REG_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[84].getValue(nIndex)); }
	public void set_COMP_REG_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[84].setValue(nIndex, value); }
	public int get_COMP_REG_ID_size() throws FMLManipulationException { return (this.fmlBuffer[84].getCount()); }


	public Double get_KOB(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[85].getValue(nIndex)); }
	public void set_KOB(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[85].setValue(nIndex, value); }
	public int get_KOB_size() throws FMLManipulationException { return (this.fmlBuffer[85].getCount()); }


	public String get_MIDDLE_INITIAL(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[86].getValue(nIndex)); }
	public void set_MIDDLE_INITIAL(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[86].setValue(nIndex, value); }
	public int get_MIDDLE_INITIAL_size() throws FMLManipulationException { return (this.fmlBuffer[86].getCount()); }


	public String get_TELEMARKET_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[87].getValue(nIndex)); }
	public void set_TELEMARKET_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[87].setValue(nIndex, value); }
	public int get_TELEMARKET_ID_size() throws FMLManipulationException { return (this.fmlBuffer[87].getCount()); }


	public Integer get_CONV_RUN_NO(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[88].getValue(nIndex))); }
	public void set_CONV_RUN_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[88].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_CONV_RUN_NO_size() throws FMLManipulationException { return (this.fmlBuffer[88].getCount()); }


	public String get_NAME_TITLE_SALUTATION(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[89].getValue(nIndex)); }
	public void set_NAME_TITLE_SALUTATION(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[89].setValue(nIndex, value); }
	public int get_NAME_TITLE_SALUTATION_size() throws FMLManipulationException { return (this.fmlBuffer[89].getCount()); }


	public String get_NATIONALITY_CD(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[90].getValue(nIndex)); }
	public void set_NATIONALITY_CD(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[90].setValue(nIndex, value); }
	public int get_NATIONALITY_CD_size() throws FMLManipulationException { return (this.fmlBuffer[90].getCount()); }


	public String get_GENDER(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[91].getValue(nIndex))); }
	public void set_GENDER(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[91].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_GENDER_size() throws FMLManipulationException { return (this.fmlBuffer[91].getCount()); }


	public String get_MARITAL_STATUS(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[92].getValue(nIndex)); }
	public void set_MARITAL_STATUS(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[92].setValue(nIndex, value); }
	public int get_MARITAL_STATUS_size() throws FMLManipulationException { return (this.fmlBuffer[92].getCount()); }


	public String get_ROLE_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[93].getValue(nIndex))); }
	public void set_ROLE_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[93].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ROLE_IND_size() throws FMLManipulationException { return (this.fmlBuffer[93].getCount()); }


	public String get_ADR_MODE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[94].getValue(nIndex))); }
	public void set_ADR_MODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[94].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ADR_MODE_size() throws FMLManipulationException { return (this.fmlBuffer[94].getCount()); }


	public String get_ADR_UP_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[95].getValue(nIndex))); }
	public void set_ADR_UP_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[95].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ADR_UP_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[95].getCount()); }


	public String get_ADR_EXPIRE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[96].getValue(nIndex)); }
	public void set_ADR_EXPIRE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[96].setValue(nIndex, value); }
	public int get_ADR_EXPIRE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[96].getCount()); }


	public String get_ADDRESSRECROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[97].getValue(nIndex)); }
	public void set_ADDRESSRECROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[97].setValue(nIndex, value); }
	public int get_ADDRESSRECROWID_size() throws FMLManipulationException { return (this.fmlBuffer[97].getCount()); }


	public Integer get_ADDRESS_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[98].getValue(nIndex)); }
	public void set_ADDRESS_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[98].setValue(nIndex, value); }
	public int get_ADDRESS_ID_size() throws FMLManipulationException { return (this.fmlBuffer[98].getCount()); }


	public String get_ADDRESSRECSYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[99].getValue(nIndex)); }
	public void set_ADDRESSRECSYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[99].setValue(nIndex, value); }
	public int get_ADDRESSRECSYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[99].getCount()); }


	public String get_ADDRESSRECSYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[100].getValue(nIndex)); }
	public void set_ADDRESSRECSYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[100].setValue(nIndex, value); }
	public int get_ADDRESSRECSYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[100].getCount()); }


	public Integer get_ADDRESSRECOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[101].getValue(nIndex)); }
	public void set_ADDRESSRECOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[101].setValue(nIndex, value); }
	public int get_ADDRESSRECOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[101].getCount()); }


	public String get_ADDRESSRECAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[102].getValue(nIndex)); }
	public void set_ADDRESSRECAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[102].setValue(nIndex, value); }
	public int get_ADDRESSRECAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[102].getCount()); }


	public String get_ADDRESSRECDL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[103].getValue(nIndex)); }
	public void set_ADDRESSRECDL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[103].setValue(nIndex, value); }
	public int get_ADDRESSRECDL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[103].getCount()); }


	public Integer get_ADDRESSRECDL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[104].getValue(nIndex))); }
	public void set_ADDRESSRECDL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[104].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ADDRESSRECDL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[104].getCount()); }


	public String get_ADR_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[105].getValue(nIndex))); }
	public void set_ADR_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[105].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ADR_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[105].getCount()); }


	public String get_ADR_STATUS(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[106].getValue(nIndex))); }
	public void set_ADR_STATUS(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[106].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_ADR_STATUS_size() throws FMLManipulationException { return (this.fmlBuffer[106].getCount()); }


	public String get_ADR_STATUS_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[107].getValue(nIndex)); }
	public void set_ADR_STATUS_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[107].setValue(nIndex, value); }
	public int get_ADR_STATUS_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[107].getCount()); }


	public String get_ADR_SECONDARY_LN(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[108].getValue(nIndex)); }
	public void set_ADR_SECONDARY_LN(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[108].setValue(nIndex, value); }
	public int get_ADR_SECONDARY_LN_size() throws FMLManipulationException { return (this.fmlBuffer[108].getCount()); }


	public String get_ADR_PRIMARY_LN(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[109].getValue(nIndex)); }
	public void set_ADR_PRIMARY_LN(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[109].setValue(nIndex, value); }
	public int get_ADR_PRIMARY_LN_size() throws FMLManipulationException { return (this.fmlBuffer[109].getCount()); }


	public String get_ADR_CITY(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[110].getValue(nIndex)); }
	public void set_ADR_CITY(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[110].setValue(nIndex, value); }
	public int get_ADR_CITY_size() throws FMLManipulationException { return (this.fmlBuffer[110].getCount()); }


	public String get_ADR_ZIP(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[111].getValue(nIndex)); }
	public void set_ADR_ZIP(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[111].setValue(nIndex, value); }
	public int get_ADR_ZIP_size() throws FMLManipulationException { return (this.fmlBuffer[111].getCount()); }


	public String get_ADR_HOUSE_NO(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[112].getValue(nIndex)); }
	public void set_ADR_HOUSE_NO(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[112].setValue(nIndex, value); }
	public int get_ADR_HOUSE_NO_size() throws FMLManipulationException { return (this.fmlBuffer[112].getCount()); }


	public String get_ADR_STREET_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[113].getValue(nIndex)); }
	public void set_ADR_STREET_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[113].setValue(nIndex, value); }
	public int get_ADR_STREET_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[113].getCount()); }


	public String get_ADR_DIRECTION(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[114].getValue(nIndex)); }
	public void set_ADR_DIRECTION(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[114].setValue(nIndex, value); }
	public int get_ADR_DIRECTION_size() throws FMLManipulationException { return (this.fmlBuffer[114].getCount()); }


	public String get_ADR_POB(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[115].getValue(nIndex)); }
	public void set_ADR_POB(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[115].setValue(nIndex, value); }
	public int get_ADR_POB_size() throws FMLManipulationException { return (this.fmlBuffer[115].getCount()); }


	public String get_ADR_COUNTRY(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[116].getValue(nIndex)); }
	public void set_ADR_COUNTRY(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[116].setValue(nIndex, value); }
	public int get_ADR_COUNTRY_size() throws FMLManipulationException { return (this.fmlBuffer[116].getCount()); }


	public String get_ADR_HOUSE_LETTER(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[117].getValue(nIndex)); }
	public void set_ADR_HOUSE_LETTER(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[117].setValue(nIndex, value); }
	public int get_ADR_HOUSE_LETTER_size() throws FMLManipulationException { return (this.fmlBuffer[117].getCount()); }


	public String get_ADR_STORY(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[118].getValue(nIndex)); }
	public void set_ADR_STORY(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[118].setValue(nIndex, value); }
	public int get_ADR_STORY_size() throws FMLManipulationException { return (this.fmlBuffer[118].getCount()); }


	public String get_ADR_DOOR_NO(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[119].getValue(nIndex)); }
	public void set_ADR_DOOR_NO(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[119].setValue(nIndex, value); }
	public int get_ADR_DOOR_NO_size() throws FMLManipulationException { return (this.fmlBuffer[119].getCount()); }


	public String get_ADR_EMAIL(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[120].getValue(nIndex)); }
	public void set_ADR_EMAIL(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[120].setValue(nIndex, value); }
	public int get_ADR_EMAIL_size() throws FMLManipulationException { return (this.fmlBuffer[120].getCount()); }


	public String get_SINCE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[121].getValue(nIndex)); }
	public void set_SINCE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[121].setValue(nIndex, value); }
	public int get_SINCE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[121].getCount()); }


	public String get_ADR_DISTRICT(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[122].getValue(nIndex)); }
	public void set_ADR_DISTRICT(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[122].setValue(nIndex, value); }
	public int get_ADR_DISTRICT_size() throws FMLManipulationException { return (this.fmlBuffer[122].getCount()); }


	public String get_CO_IND(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[123].getValue(nIndex))); }
	public void set_CO_IND(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[123].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_CO_IND_size() throws FMLManipulationException { return (this.fmlBuffer[123].getCount()); }


	public Integer get_ADDRESSRECCONV_RUN_NO(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[124].getValue(nIndex))); }
	public void set_ADDRESSRECCONV_RUN_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[124].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ADDRESSRECCONV_RUN_NO_size() throws FMLManipulationException { return (this.fmlBuffer[124].getCount()); }


	public String get_ACCOMMODATION_TYPE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[125].getValue(nIndex)); }
	public void set_ACCOMMODATION_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[125].setValue(nIndex, value); }
	public int get_ACCOMMODATION_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[125].getCount()); }


	public String get_COUNTY_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[126].getValue(nIndex)); }
	public void set_COUNTY_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[126].setValue(nIndex, value); }
	public int get_COUNTY_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[126].getCount()); }


	public String get_COMMUNITY_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[127].getValue(nIndex)); }
	public void set_COMMUNITY_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[127].setValue(nIndex, value); }
	public int get_COMMUNITY_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[127].getCount()); }


	public String get_ADR_CO_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[128].getValue(nIndex)); }
	public void set_ADR_CO_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[128].setValue(nIndex, value); }
	public int get_ADR_CO_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[128].getCount()); }


	public String get_ADR_HOUSE_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[129].getValue(nIndex)); }
	public void set_ADR_HOUSE_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[129].setValue(nIndex, value); }
	public int get_ADR_HOUSE_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[129].getCount()); }


	public String get_ADR_P1(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[130].getValue(nIndex)); }
	public void set_ADR_P1(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[130].setValue(nIndex, value); }
	public int get_ADR_P1_size() throws FMLManipulationException { return (this.fmlBuffer[130].getCount()); }


	public String get_ADR_P2(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[131].getValue(nIndex)); }
	public void set_ADR_P2(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[131].setValue(nIndex, value); }
	public int get_ADR_P2_size() throws FMLManipulationException { return (this.fmlBuffer[131].getCount()); }


	public String get_ADR_P3(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[132].getValue(nIndex)); }
	public void set_ADR_P3(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[132].setValue(nIndex, value); }
	public int get_ADR_P3_size() throws FMLManipulationException { return (this.fmlBuffer[132].getCount()); }


	public String get_ADR_P4(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[133].getValue(nIndex)); }
	public void set_ADR_P4(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[133].setValue(nIndex, value); }
	public int get_ADR_P4_size() throws FMLManipulationException { return (this.fmlBuffer[133].getCount()); }


	public String get_ADR_P5(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[134].getValue(nIndex)); }
	public void set_ADR_P5(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[134].setValue(nIndex, value); }
	public int get_ADR_P5_size() throws FMLManipulationException { return (this.fmlBuffer[134].getCount()); }


	public String get_ADR_P6(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[135].getValue(nIndex)); }
	public void set_ADR_P6(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[135].setValue(nIndex, value); }
	public int get_ADR_P6_size() throws FMLManipulationException { return (this.fmlBuffer[135].getCount()); }


	public String get_ADR_P7(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[136].getValue(nIndex)); }
	public void set_ADR_P7(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[136].setValue(nIndex, value); }
	public int get_ADR_P7_size() throws FMLManipulationException { return (this.fmlBuffer[136].getCount()); }


	public String get_ADR_P8(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[137].getValue(nIndex)); }
	public void set_ADR_P8(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[137].setValue(nIndex, value); }
	public int get_ADR_P8_size() throws FMLManipulationException { return (this.fmlBuffer[137].getCount()); }


	public String get_ADR_P9(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[138].getValue(nIndex)); }
	public void set_ADR_P9(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[138].setValue(nIndex, value); }
	public int get_ADR_P9_size() throws FMLManipulationException { return (this.fmlBuffer[138].getCount()); }


	public String get_ADR_P10(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[139].getValue(nIndex)); }
	public void set_ADR_P10(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[139].setValue(nIndex, value); }
	public int get_ADR_P10_size() throws FMLManipulationException { return (this.fmlBuffer[139].getCount()); }


	public Integer get_PSVBLPRMBUFROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[140].getValue(0)); }
	public void set_PSVBLPRMBUFROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[140].setValue(0, value); }


	public String get_BPMODE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[141].getValue(nIndex))); }
	public void set_BPMODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[141].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_BPMODE_size() throws FMLManipulationException { return (this.fmlBuffer[141].getCount()); }


	public Integer get_BPSEQNO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[142].getValue(nIndex)); }
	public void set_BPSEQNO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[142].setValue(nIndex, value); }
	public int get_BPSEQNO_size() throws FMLManipulationException { return (this.fmlBuffer[142].getCount()); }


	public String get_BPEFFDATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[143].getValue(nIndex)); }
	public void set_BPEFFDATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[143].setValue(nIndex, value); }
	public int get_BPEFFDATE_size() throws FMLManipulationException { return (this.fmlBuffer[143].getCount()); }


	public String get_BPEXPDATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[144].getValue(nIndex)); }
	public void set_BPEXPDATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[144].setValue(nIndex, value); }
	public int get_BPEXPDATE_size() throws FMLManipulationException { return (this.fmlBuffer[144].getCount()); }


	public String get_BPFORMAT(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[145].getValue(nIndex)); }
	public void set_BPFORMAT(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[145].setValue(nIndex, value); }
	public int get_BPFORMAT_size() throws FMLManipulationException { return (this.fmlBuffer[145].getCount()); }


	public String get_BPMEDIA(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[146].getValue(nIndex)); }
	public void set_BPMEDIA(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[146].setValue(nIndex, value); }
	public int get_BPMEDIA_size() throws FMLManipulationException { return (this.fmlBuffer[146].getCount()); }


	public String get_BPPRINTCATEGORY(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[147].getValue(nIndex)); }
	public void set_BPPRINTCATEGORY(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[147].setValue(nIndex, value); }
	public int get_BPPRINTCATEGORY_size() throws FMLManipulationException { return (this.fmlBuffer[147].getCount()); }


	public Integer get_BPNOOFCOPIES(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[148].getValue(nIndex))); }
	public void set_BPNOOFCOPIES(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[148].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_BPNOOFCOPIES_size() throws FMLManipulationException { return (this.fmlBuffer[148].getCount()); }


	public String get_BP_LANGUAGE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[149].getValue(nIndex)); }
	public void set_BP_LANGUAGE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[149].setValue(nIndex, value); }
	public int get_BP_LANGUAGE_size() throws FMLManipulationException { return (this.fmlBuffer[149].getCount()); }


	public String get_BP_CALL_DETAILS_MEDIA(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[150].getValue(nIndex))); }
	public void set_BP_CALL_DETAILS_MEDIA(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[150].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_BP_CALL_DETAILS_MEDIA_size() throws FMLManipulationException { return (this.fmlBuffer[150].getCount()); }


	public String get_BP_REFERENCE_INFO(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[151].getValue(nIndex)); }
	public void set_BP_REFERENCE_INFO(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[151].setValue(nIndex, value); }
	public int get_BP_REFERENCE_INFO_size() throws FMLManipulationException { return (this.fmlBuffer[151].getCount()); }



} // ArSvBilPrmInput
