package no.netcom.ninja.core.system.tuxedo.service.parameters;

import no.netcom.ninja.core.referencetables.SystemDefaultsReferenceTable;
import no.netcom.ninja.core.system.tuxedo.exception.EnvironmentException;
import no.netcom.ninja.core.system.tuxedo.exception.FMLManipulationException;
import no.netcom.ninja.core.util.TypeConverter;


/**
 * @author  Ninja - Generated by Ninja tools : created on 08-10-2019 10:40:24. Fokus 310 drop 1
 */
public class CsInsOrdInput extends ServiceInput {
	/**
	 * Creates a new instance of CsInsOrdInput
	 *
	 * @throws EnvironmentException
	 * @throws FMLManipulationException
	 */
	public CsInsOrdInput() throws EnvironmentException, FMLManipulationException {

		fmlBuffer = new FmlField[102];

		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoDirective(), 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getDefaultFokusOperatorId(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, SystemDefaultsReferenceTable.getApplicationId(), 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, SystemDefaultsReferenceTable.getTuxedoTransactionMode(), 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4, SystemDefaultsReferenceTable.getDefaultMarket(), 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, SystemDefaultsReferenceTable.getFokusEnvironmentCode(), 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoSessionId(), 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, SystemDefaultsReferenceTable.getTuxedoOnlineTrxNo(), 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("ROWID", FmlField.TYPE_STRING, 19, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("ORDER_NUMBER", FmlField.TYPE_INTEGER, -1, null, 17, 1);
		this.fmlBuffer[18] = new FmlField("SYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 18, 1);
		this.fmlBuffer[19] = new FmlField("SYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 19, 1);
		this.fmlBuffer[20] = new FmlField("PORDERHDRRECOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 20, 1);
		this.fmlBuffer[21] = new FmlField("PORDERHDRRECAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 21, 1);
		this.fmlBuffer[22] = new FmlField("DL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 22, 1);
		this.fmlBuffer[23] = new FmlField("DL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 23, 1);
		this.fmlBuffer[24] = new FmlField("EXT_PARTNER_ID", FmlField.TYPE_STRING, 6, null, 24, 1);
		this.fmlBuffer[25] = new FmlField("EXT_SRC_SYSTEM_CD", FmlField.TYPE_STRING, 6, null, 25, 1);
		this.fmlBuffer[26] = new FmlField("EXTERNAL_ORDER_ID", FmlField.TYPE_STRING, 41, null, 26, 1);
		this.fmlBuffer[27] = new FmlField("EXT_LINKED_ORDER_ID", FmlField.TYPE_STRING, 41, null, 27, 1);
		this.fmlBuffer[28] = new FmlField("EXT_COMPLETE_DATE", FmlField.TYPE_STRING, 15, null, 28, 1);
		this.fmlBuffer[29] = new FmlField("ORDER_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 29, 1);
		this.fmlBuffer[30] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 30, 1);
		this.fmlBuffer[31] = new FmlField("DEALER_CODE", FmlField.TYPE_STRING, 6, null, 31, 1);
		this.fmlBuffer[32] = new FmlField("ORDER_MODE", FmlField.TYPE_BYTE, -1, null, 32, 1);
		this.fmlBuffer[33] = new FmlField("DESCRIPTION", FmlField.TYPE_STRING, 41, null, 33, 1);
		this.fmlBuffer[34] = new FmlField("ORDER_STATUS", FmlField.TYPE_BYTE, -1, null, 34, 1);
		this.fmlBuffer[35] = new FmlField("STATUS_DATE", FmlField.TYPE_STRING, 15, null, 35, 1);
		this.fmlBuffer[36] = new FmlField("ROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 36, 1);
		this.fmlBuffer[37] = new FmlField("ORDADDINROWID", FmlField.TYPE_STRING, 19, null, 37, 600);
		this.fmlBuffer[38] = new FmlField("ORDADDINORDER_NUMBER", FmlField.TYPE_INTEGER, -1, null, 38, 600);
		this.fmlBuffer[39] = new FmlField("FIELD_NAME", FmlField.TYPE_STRING, 31, null, 39, 600);
		this.fmlBuffer[40] = new FmlField("ORDADDINSYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 40, 600);
		this.fmlBuffer[41] = new FmlField("ORDADDINSYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 41, 600);
		this.fmlBuffer[42] = new FmlField("ORDADDINOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 42, 600);
		this.fmlBuffer[43] = new FmlField("ORDADDINAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 43, 600);
		this.fmlBuffer[44] = new FmlField("ORDADDINDL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 44, 600);
		this.fmlBuffer[45] = new FmlField("ORDADDINDL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 45, 600);
		this.fmlBuffer[46] = new FmlField("FIELD_VALUE", FmlField.TYPE_STRING, 256, null, 46, 600);
		this.fmlBuffer[47] = new FmlField("PORDDTLSBUFROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 47, 1);
		this.fmlBuffer[48] = new FmlField("ORDDTLSROWID", FmlField.TYPE_STRING, 19, null, 48, 600);
		this.fmlBuffer[49] = new FmlField("ORDDTLSORDER_NUMBER", FmlField.TYPE_INTEGER, -1, null, 49, 600);
		this.fmlBuffer[50] = new FmlField("ORDER_LINE_NO", FmlField.TYPE_INTEGER, -1, null, 50, 600);
		this.fmlBuffer[51] = new FmlField("ORDDTLSSYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 51, 600);
		this.fmlBuffer[52] = new FmlField("ORDDTLSSYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 52, 600);
		this.fmlBuffer[53] = new FmlField("ORDDTLSOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 53, 600);
		this.fmlBuffer[54] = new FmlField("ORDDTLSAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 54, 600);
		this.fmlBuffer[55] = new FmlField("ORDDTLSDL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 55, 600);
		this.fmlBuffer[56] = new FmlField("ORDDTLSDL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 56, 600);
		this.fmlBuffer[57] = new FmlField("EXT_TRX_ID", FmlField.TYPE_STRING, 41, null, 57, 600);
		this.fmlBuffer[58] = new FmlField("EXT_LINKED_TRX_ID", FmlField.TYPE_STRING, 41, null, 58, 600);
		this.fmlBuffer[59] = new FmlField("EXT_PRODUCT_ID", FmlField.TYPE_STRING, 41, null, 59, 600);
		this.fmlBuffer[60] = new FmlField("EXT_COST_AMOUNT", FmlField.TYPE_DOUBLE, -1, null, 60, 600);
		this.fmlBuffer[61] = new FmlField("SUBSCRIBER_NO", FmlField.TYPE_STRING, 21, null, 61, 600);
		this.fmlBuffer[62] = new FmlField("FEATURE_CODE", FmlField.TYPE_STRING, 7, null, 62, 600);
		this.fmlBuffer[63] = new FmlField("ADJ_REASON_CODE", FmlField.TYPE_STRING, 7, null, 63, 600);
		this.fmlBuffer[64] = new FmlField("AMOUNT", FmlField.TYPE_DOUBLE, -1, null, 64, 600);
		this.fmlBuffer[65] = new FmlField("BILL_COMMENT", FmlField.TYPE_STRING, 501, null, 65, 600);
		this.fmlBuffer[66] = new FmlField("ENT_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 66, 600);
		this.fmlBuffer[67] = new FmlField("QUANTITY", FmlField.TYPE_INTEGER, -1, null, 67, 600);
		this.fmlBuffer[68] = new FmlField("CHARGE_CREATE_DATE", FmlField.TYPE_STRING, 15, null, 68, 600);
		this.fmlBuffer[69] = new FmlField("PORDLNADDINBUFROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 69, 1);
		this.fmlBuffer[70] = new FmlField("ORDLNADDINROWID", FmlField.TYPE_STRING, 19, null, 70, 600);
		this.fmlBuffer[71] = new FmlField("ORDLNADDINORDER_NUMBER", FmlField.TYPE_INTEGER, -1, null, 71, 600);
		this.fmlBuffer[72] = new FmlField("ORDLNADDINORDER_LINE_NO", FmlField.TYPE_INTEGER, -1, null, 72, 600);
		this.fmlBuffer[73] = new FmlField("ORDLNADDINFIELD_NAME", FmlField.TYPE_STRING, 31, null, 73, 600);
		this.fmlBuffer[74] = new FmlField("ORDLNADDINSYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 74, 600);
		this.fmlBuffer[75] = new FmlField("ORDLNADDINSYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 75, 600);
		this.fmlBuffer[76] = new FmlField("ORDLNADDINOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 76, 600);
		this.fmlBuffer[77] = new FmlField("ORDLNADDINAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 77, 600);
		this.fmlBuffer[78] = new FmlField("ORDLNADDINDL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 78, 600);
		this.fmlBuffer[79] = new FmlField("ORDLNADDINDL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 79, 600);
		this.fmlBuffer[80] = new FmlField("ORDLNADDINFIELD_VALUE", FmlField.TYPE_STRING, 256, null, 80, 600);
		this.fmlBuffer[81] = new FmlField("PORDPYMLISTROWCOUNT", FmlField.TYPE_INTEGER, -1, null, 81, 1);
		this.fmlBuffer[82] = new FmlField("ORDPYMLISTROWID", FmlField.TYPE_STRING, 19, null, 82, 50);
		this.fmlBuffer[83] = new FmlField("ORDPYMLISTBAN", FmlField.TYPE_INTEGER, -1, null, 83, 50);
		this.fmlBuffer[84] = new FmlField("PAYMENT_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 84, 50);
		this.fmlBuffer[85] = new FmlField("ORDPYMLISTSYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 85, 50);
		this.fmlBuffer[86] = new FmlField("ORDPYMLISTSYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 86, 50);
		this.fmlBuffer[87] = new FmlField("ORDPYMLISTOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 87, 50);
		this.fmlBuffer[88] = new FmlField("ORDPYMLISTAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 88, 50);
		this.fmlBuffer[89] = new FmlField("ORDPYMLISTDL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 89, 50);
		this.fmlBuffer[90] = new FmlField("ORDPYMLISTDL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 90, 50);
		this.fmlBuffer[91] = new FmlField("PAYMENT_AMOUNT", FmlField.TYPE_DOUBLE, -1, null, 91, 50);
		this.fmlBuffer[92] = new FmlField("PAYMENT_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 92, 50);
		this.fmlBuffer[93] = new FmlField("ORDPYMLISTEXTERNAL_ORDER_ID", FmlField.TYPE_STRING, 41, null, 93, 50);
		this.fmlBuffer[94] = new FmlField("PAYMENT_STATUS", FmlField.TYPE_BYTE, -1, null, 94, 50);
		this.fmlBuffer[95] = new FmlField("PAYMENT_STATUS_DATE", FmlField.TYPE_STRING, 15, null, 95, 50);
		this.fmlBuffer[96] = new FmlField("AR_PYM_ENT_SEQ_NO", FmlField.TYPE_INTEGER, -1, null, 96, 50);
		this.fmlBuffer[97] = new FmlField("PAYMENT_METHOD", FmlField.TYPE_STRING, 3, null, 97, 50);
		this.fmlBuffer[98] = new FmlField("PAYMENT_SUB_METHOD", FmlField.TYPE_STRING, 3, null, 98, 50);
		this.fmlBuffer[99] = new FmlField("SOURCE_TYPE", FmlField.TYPE_BYTE, -1, null, 99, 50);
		this.fmlBuffer[100] = new FmlField("SOURCE_ID", FmlField.TYPE_STRING, 9, null, 100, 50);
		this.fmlBuffer[101] = new FmlField("REFERENCE_ID", FmlField.TYPE_STRING, 41, null, 101, 50);
	} // End of constractor

	public Integer get_GENERATION() throws FMLManipulationException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws FMLManipulationException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws FMLManipulationException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws FMLManipulationException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws FMLManipulationException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws FMLManipulationException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws FMLManipulationException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws FMLManipulationException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws FMLManipulationException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws FMLManipulationException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[15].setValue(0, value); }


	public String get_ROWID() throws FMLManipulationException { return ((String) this.fmlBuffer[16].getValue(0)); }
	public void set_ROWID(String value) throws FMLManipulationException { this.fmlBuffer[16].setValue(0, value); }


	public Integer get_ORDER_NUMBER() throws FMLManipulationException { return ((Integer) this.fmlBuffer[17].getValue(0)); }
	public void set_ORDER_NUMBER(Integer value) throws FMLManipulationException { this.fmlBuffer[17].setValue(0, value); }


	public String get_SYS_CREATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[18].getValue(0)); }
	public void set_SYS_CREATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[18].setValue(0, value); }


	public String get_SYS_UPDATE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[19].getValue(0)); }
	public void set_SYS_UPDATE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[19].setValue(0, value); }


	public Integer get_PORDERHDRRECOPERATOR_ID() throws FMLManipulationException { return ((Integer) this.fmlBuffer[20].getValue(0)); }
	public void set_PORDERHDRRECOPERATOR_ID(Integer value) throws FMLManipulationException { this.fmlBuffer[20].setValue(0, value); }


	public String get_PORDERHDRRECAPPLICATION_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[21].getValue(0)); }
	public void set_PORDERHDRRECAPPLICATION_ID(String value) throws FMLManipulationException { this.fmlBuffer[21].setValue(0, value); }


	public String get_DL_SERVICE_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[22].getValue(0)); }
	public void set_DL_SERVICE_CODE(String value) throws FMLManipulationException { this.fmlBuffer[22].setValue(0, value); }


	public Integer get_DL_UPDATE_STAMP() throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[23].getValue(0))); }
	public void set_DL_UPDATE_STAMP(Integer value) throws FMLManipulationException { this.fmlBuffer[23].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_EXT_PARTNER_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[24].getValue(0)); }
	public void set_EXT_PARTNER_ID(String value) throws FMLManipulationException { this.fmlBuffer[24].setValue(0, value); }


	public String get_EXT_SRC_SYSTEM_CD() throws FMLManipulationException { return ((String) this.fmlBuffer[25].getValue(0)); }
	public void set_EXT_SRC_SYSTEM_CD(String value) throws FMLManipulationException { this.fmlBuffer[25].setValue(0, value); }


	public String get_EXTERNAL_ORDER_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[26].getValue(0)); }
	public void set_EXTERNAL_ORDER_ID(String value) throws FMLManipulationException { this.fmlBuffer[26].setValue(0, value); }


	public String get_EXT_LINKED_ORDER_ID() throws FMLManipulationException { return ((String) this.fmlBuffer[27].getValue(0)); }
	public void set_EXT_LINKED_ORDER_ID(String value) throws FMLManipulationException { this.fmlBuffer[27].setValue(0, value); }


	public String get_EXT_COMPLETE_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[28].getValue(0)); }
	public void set_EXT_COMPLETE_DATE(String value) throws FMLManipulationException { this.fmlBuffer[28].setValue(0, value); }


	public String get_ORDER_CREATION_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[29].getValue(0)); }
	public void set_ORDER_CREATION_DATE(String value) throws FMLManipulationException { this.fmlBuffer[29].setValue(0, value); }


	public Integer get_BAN() throws FMLManipulationException { return ((Integer) this.fmlBuffer[30].getValue(0)); }
	public void set_BAN(Integer value) throws FMLManipulationException { this.fmlBuffer[30].setValue(0, value); }


	public String get_DEALER_CODE() throws FMLManipulationException { return ((String) this.fmlBuffer[31].getValue(0)); }
	public void set_DEALER_CODE(String value) throws FMLManipulationException { this.fmlBuffer[31].setValue(0, value); }


	public String get_ORDER_MODE() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[32].getValue(0))); }
	public void set_ORDER_MODE(String value) throws FMLManipulationException { this.fmlBuffer[32].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_DESCRIPTION() throws FMLManipulationException { return ((String) this.fmlBuffer[33].getValue(0)); }
	public void set_DESCRIPTION(String value) throws FMLManipulationException { this.fmlBuffer[33].setValue(0, value); }


	public String get_ORDER_STATUS() throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[34].getValue(0))); }
	public void set_ORDER_STATUS(String value) throws FMLManipulationException { this.fmlBuffer[34].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_STATUS_DATE() throws FMLManipulationException { return ((String) this.fmlBuffer[35].getValue(0)); }
	public void set_STATUS_DATE(String value) throws FMLManipulationException { this.fmlBuffer[35].setValue(0, value); }


	public Integer get_ROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[36].getValue(0)); }
	public void set_ROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[36].setValue(0, value); }


	public String get_ORDADDINROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[37].getValue(nIndex)); }
	public void set_ORDADDINROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[37].setValue(nIndex, value); }
	public int get_ORDADDINROWID_size() throws FMLManipulationException { return (this.fmlBuffer[37].getCount()); }


	public Integer get_ORDADDINORDER_NUMBER(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[38].getValue(nIndex)); }
	public void set_ORDADDINORDER_NUMBER(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[38].setValue(nIndex, value); }
	public int get_ORDADDINORDER_NUMBER_size() throws FMLManipulationException { return (this.fmlBuffer[38].getCount()); }


	public String get_FIELD_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[39].getValue(nIndex)); }
	public void set_FIELD_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[39].setValue(nIndex, value); }
	public int get_FIELD_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[39].getCount()); }


	public String get_ORDADDINSYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[40].getValue(nIndex)); }
	public void set_ORDADDINSYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[40].setValue(nIndex, value); }
	public int get_ORDADDINSYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[40].getCount()); }


	public String get_ORDADDINSYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[41].getValue(nIndex)); }
	public void set_ORDADDINSYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[41].setValue(nIndex, value); }
	public int get_ORDADDINSYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[41].getCount()); }


	public Integer get_ORDADDINOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[42].getValue(nIndex)); }
	public void set_ORDADDINOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[42].setValue(nIndex, value); }
	public int get_ORDADDINOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[42].getCount()); }


	public String get_ORDADDINAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[43].getValue(nIndex)); }
	public void set_ORDADDINAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[43].setValue(nIndex, value); }
	public int get_ORDADDINAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[43].getCount()); }


	public String get_ORDADDINDL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[44].getValue(nIndex)); }
	public void set_ORDADDINDL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[44].setValue(nIndex, value); }
	public int get_ORDADDINDL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[44].getCount()); }


	public Integer get_ORDADDINDL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[45].getValue(nIndex))); }
	public void set_ORDADDINDL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[45].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ORDADDINDL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[45].getCount()); }


	public String get_FIELD_VALUE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[46].getValue(nIndex)); }
	public void set_FIELD_VALUE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[46].setValue(nIndex, value); }
	public int get_FIELD_VALUE_size() throws FMLManipulationException { return (this.fmlBuffer[46].getCount()); }


	public Integer get_PORDDTLSBUFROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[47].getValue(0)); }
	public void set_PORDDTLSBUFROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[47].setValue(0, value); }


	public String get_ORDDTLSROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[48].getValue(nIndex)); }
	public void set_ORDDTLSROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[48].setValue(nIndex, value); }
	public int get_ORDDTLSROWID_size() throws FMLManipulationException { return (this.fmlBuffer[48].getCount()); }


	public Integer get_ORDDTLSORDER_NUMBER(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[49].getValue(nIndex)); }
	public void set_ORDDTLSORDER_NUMBER(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[49].setValue(nIndex, value); }
	public int get_ORDDTLSORDER_NUMBER_size() throws FMLManipulationException { return (this.fmlBuffer[49].getCount()); }


	public Integer get_ORDER_LINE_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[50].getValue(nIndex)); }
	public void set_ORDER_LINE_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[50].setValue(nIndex, value); }
	public int get_ORDER_LINE_NO_size() throws FMLManipulationException { return (this.fmlBuffer[50].getCount()); }


	public String get_ORDDTLSSYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[51].getValue(nIndex)); }
	public void set_ORDDTLSSYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[51].setValue(nIndex, value); }
	public int get_ORDDTLSSYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[51].getCount()); }


	public String get_ORDDTLSSYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[52].getValue(nIndex)); }
	public void set_ORDDTLSSYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[52].setValue(nIndex, value); }
	public int get_ORDDTLSSYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[52].getCount()); }


	public Integer get_ORDDTLSOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[53].getValue(nIndex)); }
	public void set_ORDDTLSOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[53].setValue(nIndex, value); }
	public int get_ORDDTLSOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[53].getCount()); }


	public String get_ORDDTLSAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[54].getValue(nIndex)); }
	public void set_ORDDTLSAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[54].setValue(nIndex, value); }
	public int get_ORDDTLSAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[54].getCount()); }


	public String get_ORDDTLSDL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[55].getValue(nIndex)); }
	public void set_ORDDTLSDL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[55].setValue(nIndex, value); }
	public int get_ORDDTLSDL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[55].getCount()); }


	public Integer get_ORDDTLSDL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[56].getValue(nIndex))); }
	public void set_ORDDTLSDL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[56].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ORDDTLSDL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[56].getCount()); }


	public String get_EXT_TRX_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[57].getValue(nIndex)); }
	public void set_EXT_TRX_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[57].setValue(nIndex, value); }
	public int get_EXT_TRX_ID_size() throws FMLManipulationException { return (this.fmlBuffer[57].getCount()); }


	public String get_EXT_LINKED_TRX_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[58].getValue(nIndex)); }
	public void set_EXT_LINKED_TRX_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[58].setValue(nIndex, value); }
	public int get_EXT_LINKED_TRX_ID_size() throws FMLManipulationException { return (this.fmlBuffer[58].getCount()); }


	public String get_EXT_PRODUCT_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[59].getValue(nIndex)); }
	public void set_EXT_PRODUCT_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[59].setValue(nIndex, value); }
	public int get_EXT_PRODUCT_ID_size() throws FMLManipulationException { return (this.fmlBuffer[59].getCount()); }


	public Double get_EXT_COST_AMOUNT(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[60].getValue(nIndex)); }
	public void set_EXT_COST_AMOUNT(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[60].setValue(nIndex, value); }
	public int get_EXT_COST_AMOUNT_size() throws FMLManipulationException { return (this.fmlBuffer[60].getCount()); }


	public String get_SUBSCRIBER_NO(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[61].getValue(nIndex)); }
	public void set_SUBSCRIBER_NO(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[61].setValue(nIndex, value); }
	public int get_SUBSCRIBER_NO_size() throws FMLManipulationException { return (this.fmlBuffer[61].getCount()); }


	public String get_FEATURE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[62].getValue(nIndex)); }
	public void set_FEATURE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[62].setValue(nIndex, value); }
	public int get_FEATURE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[62].getCount()); }


	public String get_ADJ_REASON_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[63].getValue(nIndex)); }
	public void set_ADJ_REASON_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[63].setValue(nIndex, value); }
	public int get_ADJ_REASON_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[63].getCount()); }


	public Double get_AMOUNT(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[64].getValue(nIndex)); }
	public void set_AMOUNT(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[64].setValue(nIndex, value); }
	public int get_AMOUNT_size() throws FMLManipulationException { return (this.fmlBuffer[64].getCount()); }


	public String get_BILL_COMMENT(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[65].getValue(nIndex)); }
	public void set_BILL_COMMENT(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[65].setValue(nIndex, value); }
	public int get_BILL_COMMENT_size() throws FMLManipulationException { return (this.fmlBuffer[65].getCount()); }


	public Integer get_ENT_SEQ_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[66].getValue(nIndex)); }
	public void set_ENT_SEQ_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[66].setValue(nIndex, value); }
	public int get_ENT_SEQ_NO_size() throws FMLManipulationException { return (this.fmlBuffer[66].getCount()); }


	public Integer get_QUANTITY(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[67].getValue(nIndex)); }
	public void set_QUANTITY(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[67].setValue(nIndex, value); }
	public int get_QUANTITY_size() throws FMLManipulationException { return (this.fmlBuffer[67].getCount()); }


	public String get_CHARGE_CREATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[68].getValue(nIndex)); }
	public void set_CHARGE_CREATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[68].setValue(nIndex, value); }
	public int get_CHARGE_CREATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[68].getCount()); }


	public Integer get_PORDLNADDINBUFROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[69].getValue(0)); }
	public void set_PORDLNADDINBUFROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[69].setValue(0, value); }


	public String get_ORDLNADDINROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[70].getValue(nIndex)); }
	public void set_ORDLNADDINROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[70].setValue(nIndex, value); }
	public int get_ORDLNADDINROWID_size() throws FMLManipulationException { return (this.fmlBuffer[70].getCount()); }


	public Integer get_ORDLNADDINORDER_NUMBER(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[71].getValue(nIndex)); }
	public void set_ORDLNADDINORDER_NUMBER(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[71].setValue(nIndex, value); }
	public int get_ORDLNADDINORDER_NUMBER_size() throws FMLManipulationException { return (this.fmlBuffer[71].getCount()); }


	public Integer get_ORDLNADDINORDER_LINE_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[72].getValue(nIndex)); }
	public void set_ORDLNADDINORDER_LINE_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[72].setValue(nIndex, value); }
	public int get_ORDLNADDINORDER_LINE_NO_size() throws FMLManipulationException { return (this.fmlBuffer[72].getCount()); }


	public String get_ORDLNADDINFIELD_NAME(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[73].getValue(nIndex)); }
	public void set_ORDLNADDINFIELD_NAME(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[73].setValue(nIndex, value); }
	public int get_ORDLNADDINFIELD_NAME_size() throws FMLManipulationException { return (this.fmlBuffer[73].getCount()); }


	public String get_ORDLNADDINSYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[74].getValue(nIndex)); }
	public void set_ORDLNADDINSYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[74].setValue(nIndex, value); }
	public int get_ORDLNADDINSYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[74].getCount()); }


	public String get_ORDLNADDINSYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[75].getValue(nIndex)); }
	public void set_ORDLNADDINSYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[75].setValue(nIndex, value); }
	public int get_ORDLNADDINSYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[75].getCount()); }


	public Integer get_ORDLNADDINOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[76].getValue(nIndex)); }
	public void set_ORDLNADDINOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[76].setValue(nIndex, value); }
	public int get_ORDLNADDINOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[76].getCount()); }


	public String get_ORDLNADDINAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[77].getValue(nIndex)); }
	public void set_ORDLNADDINAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[77].setValue(nIndex, value); }
	public int get_ORDLNADDINAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[77].getCount()); }


	public String get_ORDLNADDINDL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[78].getValue(nIndex)); }
	public void set_ORDLNADDINDL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[78].setValue(nIndex, value); }
	public int get_ORDLNADDINDL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[78].getCount()); }


	public Integer get_ORDLNADDINDL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[79].getValue(nIndex))); }
	public void set_ORDLNADDINDL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[79].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ORDLNADDINDL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[79].getCount()); }


	public String get_ORDLNADDINFIELD_VALUE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[80].getValue(nIndex)); }
	public void set_ORDLNADDINFIELD_VALUE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[80].setValue(nIndex, value); }
	public int get_ORDLNADDINFIELD_VALUE_size() throws FMLManipulationException { return (this.fmlBuffer[80].getCount()); }


	public Integer get_PORDPYMLISTROWCOUNT() throws FMLManipulationException { return ((Integer) this.fmlBuffer[81].getValue(0)); }
	public void set_PORDPYMLISTROWCOUNT(Integer value) throws FMLManipulationException { this.fmlBuffer[81].setValue(0, value); }


	public String get_ORDPYMLISTROWID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[82].getValue(nIndex)); }
	public void set_ORDPYMLISTROWID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[82].setValue(nIndex, value); }
	public int get_ORDPYMLISTROWID_size() throws FMLManipulationException { return (this.fmlBuffer[82].getCount()); }


	public Integer get_ORDPYMLISTBAN(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[83].getValue(nIndex)); }
	public void set_ORDPYMLISTBAN(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[83].setValue(nIndex, value); }
	public int get_ORDPYMLISTBAN_size() throws FMLManipulationException { return (this.fmlBuffer[83].getCount()); }


	public Integer get_PAYMENT_SEQ_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[84].getValue(nIndex)); }
	public void set_PAYMENT_SEQ_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[84].setValue(nIndex, value); }
	public int get_PAYMENT_SEQ_NO_size() throws FMLManipulationException { return (this.fmlBuffer[84].getCount()); }


	public String get_ORDPYMLISTSYS_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[85].getValue(nIndex)); }
	public void set_ORDPYMLISTSYS_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[85].setValue(nIndex, value); }
	public int get_ORDPYMLISTSYS_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[85].getCount()); }


	public String get_ORDPYMLISTSYS_UPDATE_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[86].getValue(nIndex)); }
	public void set_ORDPYMLISTSYS_UPDATE_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[86].setValue(nIndex, value); }
	public int get_ORDPYMLISTSYS_UPDATE_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[86].getCount()); }


	public Integer get_ORDPYMLISTOPERATOR_ID(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[87].getValue(nIndex)); }
	public void set_ORDPYMLISTOPERATOR_ID(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[87].setValue(nIndex, value); }
	public int get_ORDPYMLISTOPERATOR_ID_size() throws FMLManipulationException { return (this.fmlBuffer[87].getCount()); }


	public String get_ORDPYMLISTAPPLICATION_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[88].getValue(nIndex)); }
	public void set_ORDPYMLISTAPPLICATION_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[88].setValue(nIndex, value); }
	public int get_ORDPYMLISTAPPLICATION_ID_size() throws FMLManipulationException { return (this.fmlBuffer[88].getCount()); }


	public String get_ORDPYMLISTDL_SERVICE_CODE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[89].getValue(nIndex)); }
	public void set_ORDPYMLISTDL_SERVICE_CODE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[89].setValue(nIndex, value); }
	public int get_ORDPYMLISTDL_SERVICE_CODE_size() throws FMLManipulationException { return (this.fmlBuffer[89].getCount()); }


	public Integer get_ORDPYMLISTDL_UPDATE_STAMP(int nIndex) throws FMLManipulationException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[90].getValue(nIndex))); }
	public void set_ORDPYMLISTDL_UPDATE_STAMP(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[90].setValue(nIndex, TypeConverter.integerToShort(value)); }
	public int get_ORDPYMLISTDL_UPDATE_STAMP_size() throws FMLManipulationException { return (this.fmlBuffer[90].getCount()); }


	public Double get_PAYMENT_AMOUNT(int nIndex) throws FMLManipulationException { return ((Double) this.fmlBuffer[91].getValue(nIndex)); }
	public void set_PAYMENT_AMOUNT(int nIndex, Double value) throws FMLManipulationException { this.fmlBuffer[91].setValue(nIndex, value); }
	public int get_PAYMENT_AMOUNT_size() throws FMLManipulationException { return (this.fmlBuffer[91].getCount()); }


	public String get_PAYMENT_CREATION_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[92].getValue(nIndex)); }
	public void set_PAYMENT_CREATION_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[92].setValue(nIndex, value); }
	public int get_PAYMENT_CREATION_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[92].getCount()); }


	public String get_ORDPYMLISTEXTERNAL_ORDER_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[93].getValue(nIndex)); }
	public void set_ORDPYMLISTEXTERNAL_ORDER_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[93].setValue(nIndex, value); }
	public int get_ORDPYMLISTEXTERNAL_ORDER_ID_size() throws FMLManipulationException { return (this.fmlBuffer[93].getCount()); }


	public String get_PAYMENT_STATUS(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[94].getValue(nIndex))); }
	public void set_PAYMENT_STATUS(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[94].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_PAYMENT_STATUS_size() throws FMLManipulationException { return (this.fmlBuffer[94].getCount()); }


	public String get_PAYMENT_STATUS_DATE(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[95].getValue(nIndex)); }
	public void set_PAYMENT_STATUS_DATE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[95].setValue(nIndex, value); }
	public int get_PAYMENT_STATUS_DATE_size() throws FMLManipulationException { return (this.fmlBuffer[95].getCount()); }


	public Integer get_AR_PYM_ENT_SEQ_NO(int nIndex) throws FMLManipulationException { return ((Integer) this.fmlBuffer[96].getValue(nIndex)); }
	public void set_AR_PYM_ENT_SEQ_NO(int nIndex, Integer value) throws FMLManipulationException { this.fmlBuffer[96].setValue(nIndex, value); }
	public int get_AR_PYM_ENT_SEQ_NO_size() throws FMLManipulationException { return (this.fmlBuffer[96].getCount()); }


	public String get_PAYMENT_METHOD(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[97].getValue(nIndex)); }
	public void set_PAYMENT_METHOD(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[97].setValue(nIndex, value); }
	public int get_PAYMENT_METHOD_size() throws FMLManipulationException { return (this.fmlBuffer[97].getCount()); }


	public String get_PAYMENT_SUB_METHOD(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[98].getValue(nIndex)); }
	public void set_PAYMENT_SUB_METHOD(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[98].setValue(nIndex, value); }
	public int get_PAYMENT_SUB_METHOD_size() throws FMLManipulationException { return (this.fmlBuffer[98].getCount()); }


	public String get_SOURCE_TYPE(int nIndex) throws FMLManipulationException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[99].getValue(nIndex))); }
	public void set_SOURCE_TYPE(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[99].setValue(nIndex, TypeConverter.stringToByte(value)); }
	public int get_SOURCE_TYPE_size() throws FMLManipulationException { return (this.fmlBuffer[99].getCount()); }


	public String get_SOURCE_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[100].getValue(nIndex)); }
	public void set_SOURCE_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[100].setValue(nIndex, value); }
	public int get_SOURCE_ID_size() throws FMLManipulationException { return (this.fmlBuffer[100].getCount()); }


	public String get_REFERENCE_ID(int nIndex) throws FMLManipulationException { return ((String) this.fmlBuffer[101].getValue(nIndex)); }
	public void set_REFERENCE_ID(int nIndex, String value) throws FMLManipulationException { this.fmlBuffer[101].setValue(nIndex, value); }
	public int get_REFERENCE_ID_size() throws FMLManipulationException { return (this.fmlBuffer[101].getCount()); }



} // CsInsOrdInput
